import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    
    // Verificar que es llamado como scheduled task (admin o sistema)
    const user = await base44.auth.me();
    if (user?.role !== 'admin') {
      return Response.json({ error: 'Unauthorized' }, { status: 403 });
    }

    const currentDay = new Date().getDate();
    const currentMonth = new Date().getMonth() + 1;
    const currentYear = new Date().getFullYear();
    const monthYear = `${currentYear}-${String(currentMonth).padStart(2, '0')}`;
    const nextMonth = currentMonth === 12 ? 1 : currentMonth + 1;
    const nextMonthYear = currentMonth === 12 ? `${currentYear + 1}-01` : `${currentYear}-${String(nextMonth).padStart(2, '0')}`;

    console.log(`Running briefing reminders check - Day ${currentDay} of ${currentMonth}/${currentYear}`);

    // Obtener todos los profesionales con Plan Ads+
    const subscriptions = await base44.asServiceRole.entities.Subscription.filter({
      estado: 'activo'
    });

    const adsPlusUserIds = subscriptions
      .filter(sub => sub.plan_id === 'plan_adsplus')
      .map(sub => sub.user_id);

    console.log(`Found ${adsPlusUserIds.length} Ads+ subscribers`);

    let remindersSent = 0;
    let autoGeneratedCount = 0;

    for (const userId of adsPlusUserIds) {
      try {
        // Obtener perfil profesional
        const profiles = await base44.asServiceRole.entities.ProfessionalProfile.filter({
          user_id: userId
        }).limit(1);

        if (profiles.length === 0) continue;

        const profile = profiles[0];
        const professionalName = profile.business_name || profile.user_id;

        // Verificar si ya tiene briefing para este mes
        const currentBriefings = await base44.asServiceRole.entities.AdsBriefing.filter({
          professional_id: userId,
          month_year: monthYear
        }).limit(1);

        const hasCurrentBriefing = currentBriefings.length > 0;

        // DÍA 1: Recordatorio inicial
        if (currentDay === 1 && !hasCurrentBriefing) {
          await sendReminder(userId, 'day1', professionalName, currentMonth);
          remindersSent++;
        }

        // DÍA 3: Recordatorio intermedio
        if (currentDay === 3 && !hasCurrentBriefing) {
          await sendReminder(userId, 'day3', professionalName, currentMonth);
          remindersSent++;
        }

        // DÍA 5: Recordatorio urgente por la mañana
        if (currentDay === 5 && !hasCurrentBriefing) {
          await sendReminder(userId, 'day5_urgent', professionalName, currentMonth);
          remindersSent++;
        }

        // DÍA 6: Auto-generar briefing si no hay
        if (currentDay === 6 && !hasCurrentBriefing) {
          // Buscar último briefing completado
          const previousBriefings = await base44.asServiceRole.entities.AdsBriefing.filter({
            professional_id: userId,
            status: 'completed'
          }, '-month_year', 1);

          if (previousBriefings.length > 0) {
            const lastBriefing = previousBriefings[0];
            
            // Duplicar briefing anterior para este mes
            await base44.asServiceRole.entities.AdsBriefing.create({
              professional_id: userId,
              professional_name: professionalName,
              month_year: monthYear,
              platform: lastBriefing.platform,
              goal: lastBriefing.goal,
              top_services: lastBriefing.top_services || [],
              service_area: lastBriefing.service_area || '',
              special_offer: lastBriefing.special_offer || '',
              images_provided: lastBriefing.images_provided || [],
              video_url: lastBriefing.video_url || '',
              best_testimonials: lastBriefing.best_testimonials || '',
              client_sources_now: lastBriefing.client_sources_now || [],
              client_profile: lastBriefing.client_profile || '',
              additional_notes: lastBriefing.additional_notes || '',
              included_budget_eur: 30,
              budget_tier: lastBriefing.budget_tier || 'standard',
              auto_generated: true,
              status: 'submitted',
              campaign_status: 'pending',
              submitted_at: new Date().toISOString()
            });

            // Notificar al profesional
            await sendNotification(userId, 'auto_generated', professionalName, currentMonth);
            autoGeneratedCount++;
          } else {
            // Sin briefing anterior → crear uno básico
            await base44.asServiceRole.entities.AdsBriefing.create({
              professional_id: userId,
              professional_name: professionalName,
              month_year: monthYear,
              platform: 'facebook', // Default
              goal: 'more_leads', // Default
              included_budget_eur: 30,
              budget_tier: 'standard',
              auto_generated: true,
              status: 'submitted',
              campaign_status: 'pending',
              submitted_at: new Date().toISOString()
            });

            await sendNotification(userId, 'auto_generated_default', professionalName, currentMonth);
            autoGeneratedCount++;
          }
        }
      } catch (error) {
        console.error(`Error processing user ${userId}:`, error);
      }
    }

    return Response.json({
      success: true,
      remindersSent,
      autoGeneratedCount,
      processedAt: new Date().toISOString()
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});

async function sendReminder(userId, reminderType, professionalName, month) {
  const monthNames = [
    "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
    "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
  ];

  const messages = {
    day1: {
      title: '📢 Es hora de configurar tu campaña',
      body: `Hola ${professionalName}, es momento de configurar tu campaña de ${monthNames[month - 1]}. Solo 2 minutos.`,
      priority: 'medium'
    },
    day3: {
      title: '⏰ Quedan 2 días',
      body: `Hola ${professionalName}, recuerda configurar tu campaña de ${monthNames[month - 1]}. Tienes 2 días antes del cierre.`,
      priority: 'medium'
    },
    day5_urgent: {
      title: '⚠️ Último día para configurar',
      body: `Hola ${professionalName}, hoy es el último día para configurar tu campaña de ${monthNames[month - 1]}. Si no lo haces, mantendremos la configuración anterior.`,
      priority: 'high'
    }
  };

  const message = messages[reminderType];

  try {
    // Crear notificación en la base de datos
    await base44.asServiceRole.entities.Notification.create({
      user_id: userId,
      type: 'ads briefing_reminder',
      title: message.title,
      message: message.body,
      link: '/mi-campana',
      priority: message.priority,
      is_read: false
    });

    // Enviar push notification
    await base44.functions.invoke('sendPushNotification', {
      userId,
      title: message.title,
      body: message.body,
      url: 'https://misautonomos.es/mi-campana'
    });

    console.log(`Sent ${reminderType} reminder to ${userId}`);
  } catch (error) {
    console.error(`Failed to send ${reminderType} reminder to ${userId}:`, error);
  }
}

async function sendNotification(userId, notificationType, professionalName, month) {
  const monthNames = [
    "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
    "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
  ];

  const messages = {
    auto_generated: {
      title: '📋 Briefing autogenerado',
      body: `Hola ${professionalName}, hemos mantenido tu campaña de ${monthNames[month - 1]} basada en el mes anterior para no perder el mes. Puedes modificarla el próximo briefing.`,
      priority: 'medium'
    },
    auto_generated_default: {
      title: '📋 Briefing autogenerado',
      body: `Hola ${professionalName}, hemos creado una campaña básica para ${monthNames[month - 1]} ya que no tenías configuración anterior. Contacta con soporte si necesitas cambios.`,
      priority: 'medium'
    }
  };

  const message = messages[notificationType];

  try {
    await base44.asServiceRole.entities.Notification.create({
      user_id: userId,
      type: 'ads briefing_auto_generated',
      title: message.title,
      message: message.body,
      link: '/mi-campana',
      priority: message.priority,
      is_read: false
    });

    await base44.functions.invoke('sendPushNotification', {
      userId,
      title: message.title,
      body: message.body,
      url: 'https://misautonomos.es/mi-campana'
    });

    console.log(`Sent ${notificationType} notification to ${userId}`);
  } catch (error) {
    console.error(`Failed to send ${notificationType} notification to ${userId}:`, error);
  }
}