import React, { createContext, useContext, useState, useEffect } from 'react';
import { Globe } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

const translations = {
  es: {
    // Navigation
    searchFreelancers: 'Buscar Autónomos',
    messages: 'Mensajes',
    favorites: 'Favoritos',
    myProfile: 'Mi Perfil',
    mySubscription: 'Mi Suscripción',
    administration: 'Administración',
    viewPlans: 'Ver Planes',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
    becomeFreelancer: 'Hazte autónomo',
    becomeClient: 'Hazte cliente',
    back: 'Volver',
    contact: 'Contacto',
    
    // Hero
    heroTitle: 'Encuentra tu autónomo de confianza',
    heroSubtitle: 'Conecta con profesionales verificados cerca de ti. Rápido, fácil y seguro.',
    chooseHow: '¿Cómo quieres usar MisAutónomos?',
    imFreelancer: 'Soy autónomo',
    imClient: 'Busco servicios',
    
    // Search
    filters: 'Filtros de búsqueda',
    search: 'Buscar servicio, empresa...',
    allCategories: 'Todas las categorías',
    allProvinces: 'Todas las provincias',
    allCities: 'Todas las ciudades',
    freelancersAvailable: 'autónomos disponibles',
    verifiedProfessionals: 'Profesionales verificados',
    noResults: 'No se encontraron resultados',
    tryDifferentFilters: 'Intenta con otros filtros o busca en otra ubicación',
    viewAll: 'Ver todos',
    discoverFreelancers: 'Descubrir autónomos',
    viewProfile: 'Ver perfil',
    findProfessionals: 'Encuentra profesionales',
    connectWithVerified: 'Conecta con profesionales verificados cerca de ti',
    phoneNumber: 'Número de teléfono',
    callFromYourPhone: 'Llama desde tu teléfono',
    copied: 'Copiado',
    copyNumber: 'Copiar número',
    contactViaWhatsApp: 'Contacta por WhatsApp',
    openWhatsApp: 'Abrir WhatsApp',
    phoneCopied: 'Número copiado',
    professionals: 'autónomos',
    
    // Categories
    'Electricista': 'Electricista',
    'Fontanero': 'Fontanero',
    'Carpintero': 'Carpintero',
    'Albañil / Reformas': 'Albañil / Reformas',
    'Pintor': 'Pintor',
    'Jardinero': 'Jardinero',
    'Transportista': 'Transportista',
    'Autónomo de limpieza': 'Autónomo de limpieza',
    'Cerrajero': 'Cerrajero',
    'Instalador de aire acondicionado': 'Instalador de aire acondicionado',
    'Mantenimiento general': 'Mantenimiento general',
    'Asesoría o gestoría': 'Asesoría o gestoría',
    'Empresa multiservicios': 'Empresa multiservicios',
    'Otro tipo de servicio profesional': 'Otro tipo de servicio',
    
    // Cards & Profile
    verified: 'Verificado',
    availableNow: 'Disponible ahora',
    until: 'Hasta las',
    call: 'Llamar',
    callPhone: 'Llamar por teléfono móvil',
    whatsapp: 'WhatsApp',
    chat: 'Chat directo',
    sendDirectMessage: 'Enviar mensaje directo',
    workArea: 'Zona de trabajo',
    hourRate: 'Tarifa media',
    noOpinions: 'Sin opiniones aún',
    workGallery: 'Galería de Trabajos',
    reviews: 'opiniones',
    review: 'opinión',
    information: 'Información',
    schedule: 'Horario',
    mondayFriday: 'Lunes a Viernes',
    weekends: 'Sábados, domingos y festivos',
    everyday: 'Todos los días',
    averageRate: 'Tarifa media',
    email: 'Email',
    phone: 'Teléfono',
    website: 'Sitio web',
    visitWebsite: 'Visitar sitio web',
    
    // Profile Completeness
    profileCompleteness: 'Completitud del perfil',
    completeProfileForMore: 'Completa tu perfil para recibir más clientes',
    goodProgress: 'Buen progreso, añade más detalles',
    almostPerfect: '¡Casi perfecto! Solo faltan algunos detalles',
    addTheseElements: 'Añade estos elementos para mejorar tu perfil:',
    completeNow: 'Completar ahora',
    professionalName: 'Nombre profesional',
    profilePicture: 'Foto de perfil',
    cifNif: 'NIF/CIF',
    telephoneContact: 'Teléfono',
    shortDescription: 'Descripción corta',
    categoryPlural: 'Categorías',
    photoGallery: 'Galería de fotos',
    location: 'Ubicación',
    paymentMethods: 'Formas de pago',
    
    // Onboarding - Steps
    completeYourProfile: 'Completa tu perfil profesional',
    step: 'Paso',
    of: 'de',
    identity: 'Identidad',
    activity: 'Actividad',
    zoneAndAvailability: 'Zona y disponibilidad',
    pricesAndWorkMethod: 'Precios y forma de trabajo',
    portfolioPhotos: 'Portfolio (fotos)',
    consentsAndLegal: 'Consentimientos y Legales',
    finalReview: 'Revisión final',
    next: 'Siguiente',
    saving: 'Guardando...',
    publishing: 'Publicando...',
    publishProfile: 'Publicar perfil',
    
    // Onboarding - Identity Step
    professionalNameLabel: 'Nombre profesional *',
    professionalNamePlaceholder: 'Ej: Juan Pérez - Electricista',
    characters: 'caracteres',
    cifNifLabel: 'NIF / CIF *',
    cifNifPlaceholder: '12345678A o B12345678',
    contactEmailLabel: 'Email de contacto *',
    contactEmailPlaceholder: 'tu@email.com',
    contactPhoneOptional: 'Teléfono de contacto (opcional)',
    contactPhonePlaceholder: '612345678 o +34612345678',
    noPhoneOnlyChat: 'Si no añades teléfono, solo podrán contactarte por chat interno',
    visibleContactMethods: 'Métodos de contacto visibles',
    selectHowClientsContact: 'Selecciona cómo quieres que los clientes te contacten',
    internalChat: 'Chat interno',
    alwaysActive: 'Siempre activo (obligatorio)',
    phoneCall: 'Llamada telefónica',
    requiresPhone: 'Requiere teléfono',
    addPhoneFirstWhatsApp: 'Añade un teléfono primero para activar WhatsApp',
    addPhoneFirstCall: 'Añade un teléfono primero para activar las llamadas',
    
    // Onboarding - Activity Step
    serviceCategories: 'Categorías de servicio *',
    selectAtLeastOne: '(selecciona al menos una)',
    selected: 'seleccionada',
    selectedPlural: 'seleccionadas',
    specifyYourService: 'Especifica tu servicio *',
    specifyServicePlaceholder: 'Ej: Instalador de paneles solares, Técnico de fibra óptica, etc.',
    describeYourActivity: 'Describe tu actividad profesional (mínimo 3 caracteres)',
    shortDescriptionLabel: 'Descripción corta *',
    shortDescriptionMax: '(máximo 220 caracteres)',
    shortDescriptionPlaceholder: 'Describe brevemente tus servicios...',
    minimum20: '(mínimo 20)',
    detailedDescriptionOptional: 'Descripción detallada (opcional)',
    detailedDescriptionPlaceholder: 'Añade más detalles sobre tu experiencia, servicios específicos, etc.',
    
    // Onboarding - Location Step
    indicateMainLocation: 'Indica tu ubicación principal y zona de trabajo. Los clientes podrán encontrarte en estas áreas.',
    province: 'Provincia',
    selectYourProvince: 'Selecciona tu provincia',
    city: 'Ciudad',
    locality: 'Localidad',
    selectFromList: '(selecciona de la lista)',
    selectYourCity: 'Selecciona tu ciudad',
    asMainCity: '(como ciudad principal)',
    onlyFromList: 'Solo se puede seleccionar de la lista. Si tu localidad no aparece, elige la ciudad más cercana.',
    neighborhoodOptional: 'Barrio / Municipio (opcional - texto libre)',
    neighborhoodPlaceholder: 'Ej: Centro, Chamartín, Eixample...',
    specifyNeighborhood: 'Especifica un barrio o zona específica si quieres ser más preciso (opcional)',
    yourMainLocation: 'Tu ubicación principal:',
    serviceRadius: 'Radio de servicio *',
    onlyMyZone: 'Solo mi zona',
    cityAndSurroundings: 'Ciudad y alrededores',
    metropolitanArea: 'Área metropolitana',
    provinceWide: 'Provincia',
    multipleProvinces: 'Múltiples provincias',
    howFarTravel: '¿Hasta qué distancia estás dispuesto a desplazarte?',
    availability: 'Disponibilidad',
    whenCanYouWork: '¿Cuándo puedes trabajar?',
    weekdays: 'Días laborables (Lunes–Viernes)',
    workMondayFriday: 'Trabajo de lunes a viernes',
    weekendsAndHolidays: 'Fines de semana y festivos',
    workWeekendsHolidays: 'Trabajo sábados, domingos y festivos',
    allWeek: 'Ambos (Toda la semana)',
    availableAnyDay: 'Disponible cualquier día de la semana',
    startTime: 'Hora de inicio *',
    endTime: 'Hora de fin *',
    schedulePreview: 'Horario',
    
    // Onboarding - Pricing Step
    baseRateOptional: 'Tarifa base (€/hora o por servicio) - OPCIONAL',
    baseRatePlaceholder: 'Ej: 35 (déjalo vacío si prefieres no mostrar tarifa)',
    emptyNoRate: 'Si lo dejas vacío, no se mostrará información de tarifa en tu perfil',
    invoiceType: 'Tipo de facturación *',
    freelancer: 'Autónomo',
    company: 'Sociedad',
    other: 'Otros',
    acceptedPaymentMethods: 'Formas de pago aceptadas *',
    selectAtLeastOnePayment: 'Selecciona al menos una forma de pago',
    card: 'Tarjeta',
    transfer: 'Transferencia',
    cash: 'Efectivo',
    bizum: 'Bizum',
    selectedPayment: 'Seleccionado',
    paymentMethodsSelected: 'forma(s) de pago seleccionada(s)',
    
    // Onboarding - Portfolio Step
    workPhotos: 'Fotos de trabajos realizados *',
    minimum1Photo: '(mínimo 1)',
    clickToAddPhoto: 'Haz clic para añadir una foto',
    photo: 'Foto',
    photosUploaded: 'foto(s) subida(s)',
    mainPhoto: 'Principal',
    
    // Onboarding - Legal Step
    readAndAcceptConsents: 'Lee y acepta los consentimientos necesarios para publicar tu perfil',
    acceptAllConsents: 'Aceptar todos los consentimientos',
    allConsentsAccepted: 'Todos los consentimientos aceptados',
    termsAndConditionsLabel: 'Términos y Condiciones',
    acceptTermsAndConditions: 'He leído y acepto los',
    termsAndConditions: 'Términos y Condiciones',
    ofPlatformUse: 'de uso de la plataforma MisAutónomos.',
    privacyPolicyLabel: 'Política de Privacidad',
    acceptPrivacyPolicy: 'Acepto la',
    privacyPolicy: 'Política de Privacidad',
    andDataTreatment: 'y el tratamiento de mis datos personales según el RGPD.',
    contactConsentLabel: 'Consentimiento de Contacto',
    consentClientContact: 'Consiento en que los clientes puedan contactarme a través de la plataforma para solicitar presupuestos y servicios.',
    
    // Onboarding - Review Step
    reviewAllInfo: 'Revisa toda tu información antes de publicar tu perfil profesional. Podrás editarla después desde tu panel de usuario.',
    edit: 'Editar',
    name: 'Nombre',
    nif: 'NIF',
    contactMethods: 'Métodos de contacto',
    internalChatMethod: 'Chat Interno',
    whatsappMethod: 'WhatsApp',
    phoneCallMethod: 'Llamada Telefónica',
    none: 'Ninguno',
    notSpecified: 'No especificado',
    specificService: 'Servicio específico',
    description: 'Descripción',
    noDescription: 'Sin descripción',
    locationAndAvailability: 'Ubicación y Disponibilidad',
    neighborhood: 'Municipio',
    availabilityColon: 'Disponibilidad:',
    scheduleColon: 'Horario:',
    ratesAndWorkMethod: 'Tarifas y Forma de Trabajo',
    baseRate: 'Tarifa base',
    invoicingType: 'Tipo de facturación',
    paymentMethods: 'Formas de pago',
    photos: 'Fotos',
    noPhotosAdded: 'Sin fotos añadidas',
    legalConfirmations: 'Confirmaciones legales',
    acceptTerms: 'Acepto los términos y condiciones',
    acceptPrivacy: 'Acepto la política de privacidad',
    consentContact: 'Consiento ser contactado por clientes',
    
    // Onboarding - Success
    profileActiveTitle: '¡Tu perfil profesional está activo!',
    visibleInSearches: 'Ya eres visible en las búsquedas de',
    startReceivingContacts: 'Empieza a recibir contactos de clientes interesados en tus servicios profesionales.',
    profileActive: 'Perfil activo',
    visibleInSearch: 'Visible en búsquedas',
    readyForClients: 'Listo para clientes',
    viewMyPublicProfile: 'Ver mi ficha pública',
    viewClientSearches: 'Ver búsquedas de clientes',
    editMyProfile: 'Editar mi perfil',
    tipsToStandOut: 'Consejos para destacar',
    addMorePhotos: 'Mantén tu perfil actualizado con fotos recientes de tus trabajos',
    respondFast: 'Responde rápido a los mensajes para mejorar tu posición en búsquedas',
    askForReviews: 'Pide valoraciones a tus clientes satisfechos',
    needHelp: '¿Necesitas ayuda? Contacta con soporte:',
    restrictedAccess: 'Acceso restringido',
    professionalOnlyPage: 'Esta página es solo para profesionales. Si deseas ofrecer tus servicios, primero debes seleccionar un plan.',
    viewAvailablePlans: 'Ver planes disponibles',
    
    // Validation errors
    professionalNameMinChars: 'El nombre profesional debe tener al menos 2 caracteres',
    cifNifMinChars: 'El NIF/CIF debe tener al menos 8 caracteres',
    invalidEmail: 'Email inválido',
    selectAtLeastOneContactMethod: 'Selecciona al menos un método de contacto',
    selectAtLeastOneCategory: 'Selecciona al menos una categoría',
    specifyServiceIfOther: 'Especifica tu servicio cuando seleccionas "Otro tipo de servicio profesional"',
    serviceSpecMinChars: 'La especificación del servicio debe tener al menos 3 caracteres',
    shortDescriptionMinChars: 'La descripción corta debe tener al menos 20 caracteres',
    selectProvince: 'Selecciona una provincia',
    selectCity: 'Selecciona una ciudad',
    selectAvailabilityType: 'Selecciona un tipo de disponibilidad',
    selectAtLeastOnePaymentMethod: 'Selecciona al menos una forma de pago',
    uploadAtLeast1Photo: 'Sube al menos 1 foto de tus trabajos',
    acceptTermsAndConditionsError: 'Debes aceptar los Términos y Condiciones',
    acceptPrivacyPolicyError: 'Debes aceptar la Política de Privacidad',
    consentClientContactError: 'Debes consentir ser contactado por clientes',
    errorSavingStep: 'Error al guardar: ',
    pleaseVerifyData: '. Verifica los datos.',
    completeStep: 'Completa el paso',
    beforePublishing: 'antes de publicar',
    errorSavingProfile: 'Error al guardar el perfil',
    profileCompletedAndPublished: '¡Perfil completado y publicado con éxito!',
    photoUploadSuccess: '✅ Foto subida correctamente',
    photoUploadError: '❌ Error al subir la foto',
    terms: 'términos',
    privacy: 'privacidad',
    
    // Client Onboarding
    createClientAccount: 'Crea tu cuenta de cliente',
    completeDataToSearch: 'Completa estos datos para empezar a buscar profesionales',
    freeNoHiddenCosts: '100% GRATIS - Sin costes ocultos',
    emailVerificationSent: 'Al enviar, crearemos tu cuenta y recibirás un email de verificación de MisAutónomos',
    fullName: 'Nombre completo',
    fullNamePlaceholder: 'Ej: Juan Pérez',
    emailCantChange: 'Email de tu cuenta (no se puede cambiar aquí)',
    emailVerificationInfo: 'Recibirás un email de verificación de MisAutónomos en esta dirección',
    whatServicesLooking: '¿Qué tipo de servicios buscas? *',
    createMyClientAccount: 'Crear mi cuenta de cliente',
    completeRegistration: 'Completar registro',
    redirectingToRegistration: 'Redirigiendo al registro...',
    savingYourData: 'Estamos guardando tus datos y preparando tu cuenta.',
    redirectInSeconds: 'Serás redirigido al sistema de registro en unos segundos...',
    alreadyProfessionalAccount: 'Ya tienes una cuenta profesional',
    cantCreateClientAccount: 'Tu cuenta ya está configurada como autónomo. No puedes crear una cuenta de cliente simultáneamente.',
    redirectingToProfile: 'Redirigiendo a tu perfil...',
    freeBenefit: '100% Gratis',
    noHiddenCosts: 'Sin costes ocultos',
    realReviews: 'Con valoraciones reales',
    directChat: 'Chat directo',
    immediateContact: 'Contacto inmediato',
    redirecting: 'Redirigiendo...',
    creatingAccount: 'Creando tu cuenta...',
    freeForClients: 'Al completar el registro podrás buscar y contactar con profesionales de forma gratuita',
    
    // Subscription Management
    manageProfessionalPlan: 'Gestiona tu plan profesional',
    backToProfile: 'Volver a Mi Perfil',
    noActiveSubscription: 'Sin suscripción activa',
    needPlanToAppear: 'Necesitas contratar un plan profesional para que tu perfil aparezca en las búsquedas y puedas recibir contactos de clientes.',
    verifyPaymentAdmin: 'Verificar pago (Admin)',
    verifying: 'Verificando...',
    yourPlanInfo: 'Información de tu plan',
    currentPlan: 'Plan actual',
    active: 'Activo',
    canceled: 'Cancelado',
    finished: 'Finalizado',
    trial: 'Prueba',
    startDate: 'Fecha de inicio',
    renewalExpiration: 'Renovación / Expiración',
    days: 'días',
    profileVisibleOk: 'Tu perfil es visible para todos los clientes. Todo en orden.',
    trialActive: 'Periodo de prueba activa. Tu perfil es visible para clientes.',
    daysRemainingTrial: 'días restantes de prueba gratuita. Si no cancelas antes de la fecha indicada, se realizará el cobro automático.',
    subscriptionCanceledActive: 'Suscripción cancelada. Tu plan está activo hasta el',
    profileVisibleFor: 'Tu perfil seguirá visible durante',
    moreDays: 'días más.',
    subscriptionFinishedHidden: 'Suscripción finalizada. Tu perfil ya no es visible.',
    considerReactivating: 'Considera reactivar tu plan para volver a aparecer en las búsquedas.',
    upgradeYourPlan: 'Mejora tu plan',
    saveUpTo: 'Ahorra hasta 138€/año cambiando a plan trimestral o anual',
    viewSuperiorPlans: 'Ver planes superiores',
    reactivateYourPlan: 'Reactiva tu plan',
    appearInSearches: 'Vuelve a aparecer en las búsquedas y recibe nuevos clientes',
    cancelSubscription: 'Cancelar suscripción',
    cancelTrialNoCharge: 'Si cancelas durante la prueba, no se te cobrará nada. Tu perfil dejará de aparecer inmediatamente.',
    cancelHideProfile: 'Tu perfil dejará de aparecer en las búsquedas inmediatamente, pero seguirás teniendo acceso hasta la fecha de expiración.',
    changePlan: 'Cambiar plan',
    exploreOtherPlans: 'Explora otros planes que se adapten mejor a tus necesidades',
    viewAllPlans: 'Ver todos los planes',
    confirmCancelSubscription: '¿Cancelar suscripción?',
    ifYouCancel: 'Si cancelas tu suscripción:',
    noChargeTrialCanceled: 'NO se te cobrará nada (tu prueba gratuita se cancela)',
    profileHidesImmediately: 'Tu perfil dejará de aparecer inmediatamente',
    canReactivateAnytime: 'Puedes reactivar en cualquier momento con otro plan',
    profileHidesFromSearch: 'dejará de aparecer en las búsquedas inmediatamente',
    noNewClientContacts: 'No recibirás nuevos contactos de clientes',
    accessUntil: 'Mantendrás acceso a tu cuenta hasta el',
    canReactivateSubscription: 'Podrás reactivar tu suscripción en cualquier momento',
    areYouSureContinue: '¿Estás seguro que deseas continuar?',
    noKeepActive: 'No, mantener activo',
    canceling: 'Cancelando...',
    yesCancelSubscription: 'Sí, cancelar suscripción',
    
    // Reviews
    reviewsTitle: 'Opiniones de clientes',
    noReviewsYet: 'Sin opiniones por ahora',
    beFirstReview: 'Sé el primero en dejar una opinión',
    speed: 'Rapidez',
    communication: 'Comunicación',
    quality: 'Calidad',
    priceSatisfaction: 'Precio/Satisfacción',
    reportReview: 'Reportar opinión',
    inappropriate: 'Contenido inapropiado',
    
    // Messages
    conversations: 'Conversaciones',
    noConversations: 'No hay conversaciones',
    startChatting: 'Comienza a chatear con profesionales',
    writeMessage: 'Escribe un mensaje...',
    send: 'Enviar',
    loadingMessages: 'Cargando mensajes...',
    user: 'Usuario',
    you: 'Tú',
    professional: 'Autónomo',
    client: 'Cliente',
    online: 'En línea',
    selectConversation: 'Selecciona una conversación',
    chooseContactToChat: 'Elige un contacto para comenzar a chatear',
    enterToSend: 'Presiona Enter para enviar, Shift+Enter para nueva línea',
    messageSent: 'Mensaje enviado',
    sendMessageError: 'Error al enviar el mensaje',
    prepareMessageError: 'Error al preparar el mensaje: ',
    
    // Review Dialog
    rateServiceOf: 'Valorar el servicio de',
    reviewHelpfulDescription: 'Tu opinión ayuda a otros clientes a tomar decisiones informadas',
    rapidez: 'Rapidez',
    comunicacion: 'Comunicación',
    calidadTrabajo: 'Calidad del trabajo',
    relacionCalidadPrecio: 'Relación calidad/precio',
    tellExperienceOptional: 'Cuéntanos tu experiencia (opcional)',
    experiencePlaceholder: 'Describe tu experiencia con este profesional...',
    tip: 'Consejo',
    honestReviewsHelpful: 'Las valoraciones honestas son las más útiles para la comunidad',
    warning: 'Aviso',
    alreadyReviewedMessage: 'Ya has valorado a este profesional anteriormente',
    rateAllAspects: 'Por favor, valora todos los aspectos',
    commentMinLength: 'El comentario debe tener al menos 10 caracteres',
    reviewSuccess: 'Valoración publicada correctamente',
    alreadyReviewed: 'Ya has valorado este servicio',
    reviewError: 'Error al publicar la valoración',
    alreadyReviewedInfo: 'Ya has valorado a este profesional',
    bidirectionalConversationRequired: 'Solo puedes valorar después de recibir una respuesta',
    cannotLeaveReviewNow: 'No puedes dejar una valoración ahora',
    sending: 'Enviando...',
    publishReview: 'Publicar valoración',
    noMessagesInConversation: 'No hay mensajes en esta conversación',
    contactProfessionalToStart: 'Contacta con un profesional para empezar',
    loadingMessaging: 'Cargando mensajes...',
    messagesPageDescription: 'Gestiona tus conversaciones con profesionales',
    
    // Favorites
    myFavorites: 'Mis Favoritos',
    noFavorites: 'Aún no tienes favoritos',
    addFavorites: 'Guarda tus profesionales preferidos aquí',
    remove: 'Eliminar',
    
    // Footer
    tagline: 'Tu autónomo de confianza',
    platformDescription: 'Conectamos profesionales con clientes en toda España',
    forProfessionals: 'Para Profesionales',
    forClients: 'Para Clientes',
    navigation: 'Navegación',
    legal: 'Legal',
    plansAndPricing: 'Planes y precios',
    createProfile: 'Crear perfil',
    joinAdvantages: 'Ventajas de unirse',
    helpCenter: 'Centro de ayuda',
    createFreeAccount: 'Crear cuenta gratis',
    faq: 'Preguntas frecuentes',
    cookiePolicy: 'Política de cookies',
    legalNotice: 'Aviso legal',
    allRightsReserved: 'Todos los derechos reservados',
    
    // Cookies Banner
    cookiesBannerTitle: 'Este sitio web utiliza cookies',
    cookiesBannerDescription: 'Utilizamos cookies propias y de terceros para mejorar tu experiencia de navegación y el funcionamiento del sitio. Al hacer clic en "Aceptar todas", aceptas el uso de todas las cookies. Puedes gestionar tus preferencias en "Configurar cookies".',
    acceptAllCookies: 'Aceptar todas',
    acceptEssentialCookies: 'Solo esenciales',
    configureCookies: 'Configurar cookies',
    rejectAllCookies: 'Rechazar todas',
    cookiePreferences: 'Preferencias de cookies',
    cookiePreferencesDescription: 'Gestiona qué cookies quieres permitir en MisAutónomos',
    essentialCookies: 'Cookies esenciales',
    essentialCookiesDescription: 'Necesarias para el funcionamiento básico del sitio web (autenticación, seguridad, navegación). No se pueden desactivar.',
    analyticsCookies: 'Cookies analíticas',
    analyticsCookiesDescription: 'Nos ayudan a entender cómo interactúan los usuarios con la web para mejorar la experiencia (Google Analytics).',
    marketingCookies: 'Cookies de marketing',
    marketingCookiesDescription: 'Utilizadas para mostrar publicidad relevante y medir la efectividad de nuestras campañas publicitarias.',
    alwaysActive: 'Siempre activas',
    savePreferences: 'Guardar preferencias',
    learnMoreCookies: 'Más información:',
    
    // Tickets
    supportTickets: 'Tickets de soporte',
    myTickets: 'Mis tickets',
    openTicket: 'Abrir ticket',

    // Pricing Plans
    startFreeToday: 'Empieza gratis hoy',
    twoMonthsFree: '2 MESES GRATIS',
    noCommitment: 'Sin permanencia',
    cancelAnytime: 'Cancela cuando quieras',
    securePayment: 'Pago 100% seguro',
    monthly: 'Mensual',
    quarterly: 'Trimestral',
    annual: 'Anual',
    firstTwoMonths: 'primeros 2 meses',
    then: 'Luego',
    perMonth: '/mes',
    every3Months: 'cada 3 meses',
    perYear: '/año',
    save10: '💰 Ahorra 10% - Solo 30€/mes',
    save20: '🎉 Ahorra 20% - Solo 26€/mes',
    mostPopular: 'Más popular',
    bestValue: 'Mejor valor',
    appearInSearches: 'Aparece en búsquedas',
    directChatWithClients: 'Chat directo con clientes',
    completeCRM: 'CRM completo para clientes',
    invoicingSystem: 'Sistema de facturación',
    integratedPaymentGateway: 'Pasarela de pago integrada',
    support247: 'Soporte 24/7 vía tickets',
    ratingsSystem: 'Sistema de valoraciones',
    unlimitedPhotoGallery: 'Galería de fotos ilimitada',
    jobManagement: 'Gestión de trabajos',
    startNow: 'Empezar ahora',
    clickGoToCheckout: 'Al hacer clic, irás al checkout seguro de Stripe',
    whatHappensAfter2Months: '¿Qué pasa después de los 2 meses?',
    autoChargeExplain: 'Se cobrará automáticamente según el plan elegido. Puedes cancelar antes sin coste.',
    canCancelAnytime: '¿Puedo cancelar cuando quiera?',
    noPermanenceExplain: 'Sí, sin permanencia. Cancela antes de los 60 días y no pagas nada.',
    noPlansAvailable: 'No hay planes disponibles',
    plansBeingConfigured: 'Los planes se están configurando. Intenta de nuevo en unos minutos.',
    reloadPage: 'Recargar página',
    
    // MyProfile
    myProfile: 'Mi Perfil',
    manageYourProfile: 'Gestiona tu perfil profesional',
    manageYourInformation: 'Gestiona tu información',
    visibleToClients: 'Visible para clientes',
    hiddenProfile: 'Perfil oculto',
    personalInformation: 'Información Personal',
    professionalProfile: 'Perfil Profesional',
    portfolio: 'Portfolio',
    professionalIdentity: 'Identidad Profesional',
    yearsExperience: 'Años de experiencia',
    emailContact: 'Email de contacto',
    phoneContact: 'Teléfono de contacto',
    ibanForInvoices: 'IBAN (para recibir pagos de facturas)',
    ibanHelp: 'Necesario para recibir los pagos de facturas procesadas por MisAutónomos (transferencia en 7 días)',
    servicesAndDescription: 'Servicios y Descripción',
    serviceCategory: 'Categoría de servicio (elige solo una)',
    servicesDescription: 'Descripción de tus servicios',
    editProfile: 'Editar Perfil',
    profileSaved: 'Perfil guardado correctamente',
    errorSaving: 'Error al guardar',
    uploadingPhoto: 'Subiendo foto...',
    profileUpdated: 'Perfil actualizado',
    fullNameLabel: 'Nombre completo',
    accountType: 'Tipo de cuenta',
    manageAvailability: 'Gestionar disponibilidad',
    profileActiveVisible: 'Tu perfil está activo y visible en las búsquedas. Los clientes pueden encontrarte y contactarte.',
    profilePausedHidden: 'Tu perfil está pausado. No apareces en búsquedas mientras te tomes un descanso.',
    activeAndVisible: 'Perfil activo y visible',
    clientsCanSee: 'Los clientes pueden verte en búsquedas y contactarte',
    profilePaused: 'Perfil pausado',
    usefulIfBusy: 'Útil si tienes mucho trabajo y no puedes atender nuevos clientes',
    professionalNameRequired: 'Nombre profesional *',
    locationLabel: 'Ubicación',
    selectProvincePlaceholder: 'Selecciona provincia',
    selectCityPlaceholder: 'Selecciona ciudad',
    firstChooseProvince: 'Primero elige provincia',
    ratesAndPayments: 'Tarifas y Pagos',
    baseRateOptionalLabel: 'Tarifa base (€/hora) - opcional',
    acceptedPaymentMethodsLabel: 'Formas de pago aceptadas',
    clickToAddPhotos: 'Haz clic para añadir fotos ({count}/10)',
    selectMultiple: 'Puedes seleccionar varias a la vez',
    photoNumber: 'Foto {number}',
    mainPhotoLabel: 'Principal',
    socialNetworksLabel: 'Redes Sociales',
    wantOfferServices: '¿Quieres ofrecer tus servicios?',
    becomeProfessionalAppear: 'Conviértete en autónomo y aparece en las búsquedas de clientes',
    verifyingSubscription: 'Verificando tu suscripción',
    confirmingPayment: 'Estamos confirmando tu pago y activando tu cuenta...',
    takesSeconds: 'Esto tardará solo unos segundos',
    dontCloseWindow: 'Por favor, no cierres esta ventana mientras procesamos tu pago.',
    trialPeriod: 'Periodo de prueba',
    trialEnded: 'Prueba finalizada',
    daysTrialRemaining: '{days} días de prueba restantes',
    activeSubscription: 'Suscripción activa',
    renewal: 'Renovación',
    canceledSubscription: 'Suscripción cancelada',
    finishedSubscription: 'Suscripción finalizada',
    activeUntil: 'Activo hasta {date} (no se renovará)',
    profileHidden: 'Tu perfil está oculto',
    inactiveSubscription: 'Suscripción inactiva',
    validUntil: 'Válido hasta {date}',
    reactivateToAppear: 'Reactiva tu plan para aparecer en búsquedas',
    personalDataUpdated: '✅ Datos personales actualizados',
    professionalProfileUpdated: '✅ Perfil profesional actualizado',
    profileUpdatedSuccess: '✅ Tu perfil se ha actualizado correctamente.',
    profileNowVisible: '✅ Tu perfil ahora es visible en búsquedas',
    profileNowHidden: '🔒 Tu perfil está oculto en búsquedas',
    photosAdded: '✅ {count} foto(s) añadida(s)',
    photoRemoved: 'Foto eliminada',
    errorUploadingPhotos: 'Error al subir las fotos',
    errorRemovingPhoto: 'Error al eliminar la foto',
    exceedsSize: '{filename} supera los 5MB',
    noCategory: 'Sin categoría',
    saveChanges: 'Guardar cambios',
    saving: 'Guardando...',
    
    // ProfessionalProfile  
    backToSearch: 'Volver a búsqueda',
    workGalleryTitle: 'Galería de trabajos',
    socialNetworks: 'Redes sociales',
    statistics30Days: 'Estadísticas (30 días)',
    views: 'Vistas',
    searches: 'Búsquedas',
    contacts: 'Contactos',
    clientReviews: 'Opiniones de clientes',
    
    // Common
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    previous: 'Anterior',
    confirm: 'Confirmar',
    close: 'Cerrar',
  },
  en: {
    // Navigation
    searchFreelancers: 'Find Professionals',
    messages: 'Messages',
    favorites: 'Favorites',
    myProfile: 'My Profile',
    mySubscription: 'My Subscription',
    administration: 'Administration',
    viewPlans: 'View Plans',
    logout: 'Log out',
    login: 'Log in',
    becomeFreelancer: 'Become a professional',
    becomeClient: 'Become a client',
    back: 'Back',
    contact: 'Contact',
    
    // Hero
    heroTitle: 'Find your trusted professional',
    heroSubtitle: 'Connect with verified professionals near you. Fast, easy and secure.',
    chooseHow: 'How do you want to use MisAutónomos?',
    imFreelancer: "I'm a professional",
    imClient: 'I need services',
    
    // Search
    filters: 'Search filters',
    search: 'Search service, company...',
    allCategories: 'All categories',
    allProvinces: 'All provinces',
    allCities: 'All cities',
    freelancersAvailable: 'professionals available',
    verifiedProfessionals: 'Verified professionals',
    noResults: 'No results found',
    tryDifferentFilters: 'Try different filters or search in another location',
    viewAll: 'View all',
    discoverFreelancers: 'Discover professionals',
    viewProfile: 'View profile',
    findProfessionals: 'Find professionals',
    connectWithVerified: 'Connect with verified professionals near you',
    phoneNumber: 'Phone number',
    callFromYourPhone: 'Call from your phone',
    copied: 'Copied',
    copyNumber: 'Copy number',
    contactViaWhatsApp: 'Contact via WhatsApp',
    openWhatsApp: 'Open WhatsApp',
    phoneCopied: 'Phone copied',
    professionals: 'professionals',
    
    // Categories
    'Electricista': 'Electrician',
    'Fontanero': 'Plumber',
    'Carpintero': 'Carpenter',
    'Albañil / Reformas': 'Mason / Renovations',
    'Pintor': 'Painter',
    'Jardinero': 'Gardener',
    'Transportista': 'Carrier',
    'Autónomo de limpieza': 'Cleaning Service',
    'Cerrajero': 'Locksmith',
    'Instalador de aire acondicionado': 'AC Installer',
    'Mantenimiento general': 'General Maintenance',
    'Asesoría o gestoría': 'Consulting',
    'Empresa multiservicios': 'Multi-service',
    'Otro tipo de servicio profesional': 'Other service',
    
    // Cards & Profile
    verified: 'Verified',
    availableNow: 'Available now',
    until: 'Until',
    call: 'Call',
    callPhone: 'Call mobile phone',
    whatsapp: 'WhatsApp',
    chat: 'Direct chat',
    sendDirectMessage: 'Send direct message',
    workArea: 'Work area',
    hourRate: 'Average rate',
    noOpinions: 'No reviews yet',
    workGallery: 'Work Gallery',
    reviews: 'reviews',
    review: 'review',
    information: 'Information',
    schedule: 'Schedule',
    mondayFriday: 'Monday to Friday',
    weekends: 'Weekends & Holidays',
    everyday: 'Every day',
    averageRate: 'Average rate',
    email: 'Email',
    phone: 'Phone',
    website: 'Website',
    visitWebsite: 'Visit website',
    
    // Profile Completeness
    profileCompleteness: 'Profile completeness',
    completeProfileForMore: 'Complete your profile to receive more clients',
    goodProgress: 'Good progress, add more details',
    almostPerfect: 'Almost perfect! Just a few details missing',
    addTheseElements: 'Add these elements to improve your profile:',
    completeNow: 'Complete now',
    professionalName: 'Professional name',
    profilePicture: 'Profile picture',
    cifNif: 'Tax ID',
    telephoneContact: 'Phone',
    shortDescription: 'Short description',
    categoryPlural: 'Categories',
    photoGallery: 'Photo gallery',
    location: 'Location',
    paymentMethods: 'Payment methods',
    
    // Onboarding - Steps
    completeYourProfile: 'Complete your professional profile',
    step: 'Step',
    of: 'of',
    identity: 'Identity',
    activity: 'Activity',
    zoneAndAvailability: 'Location & Availability',
    pricesAndWorkMethod: 'Pricing & Work Method',
    portfolioPhotos: 'Portfolio (photos)',
    consentsAndLegal: 'Consents & Legal',
    finalReview: 'Final Review',
    next: 'Next',
    saving: 'Saving...',
    publishing: 'Publishing...',
    publishProfile: 'Publish profile',
    
    // Onboarding - Identity Step
    professionalNameLabel: 'Professional name *',
    professionalNamePlaceholder: 'E.g.: John Smith - Electrician',
    characters: 'characters',
    cifNifLabel: 'Tax ID *',
    cifNifPlaceholder: '12345678A or B12345678',
    contactEmailLabel: 'Contact email *',
    contactEmailPlaceholder: 'your@email.com',
    contactPhoneOptional: 'Contact phone (optional)',
    contactPhonePlaceholder: '612345678 or +34612345678',
    noPhoneOnlyChat: 'Without phone, clients can only contact you via internal chat',
    visibleContactMethods: 'Visible contact methods',
    selectHowClientsContact: 'Select how you want clients to contact you',
    internalChat: 'Internal chat',
    alwaysActive: 'Always active (mandatory)',
    phoneCall: 'Phone call',
    requiresPhone: 'Requires phone',
    addPhoneFirstWhatsApp: 'Add a phone first to enable WhatsApp',
    addPhoneFirstCall: 'Add a phone first to enable calls',
    
    // Onboarding - Activity Step
    serviceCategories: 'Service categories *',
    selectAtLeastOne: '(select at least one)',
    selected: 'selected',
    selectedPlural: 'selected',
    specifyYourService: 'Specify your service *',
    specifyServicePlaceholder: 'E.g.: Solar panel installer, Fiber optic technician, etc.',
    describeYourActivity: 'Describe your professional activity (minimum 3 characters)',
    shortDescriptionLabel: 'Short description *',
    shortDescriptionMax: '(maximum 220 characters)',
    shortDescriptionPlaceholder: 'Briefly describe your services...',
    minimum20: '(minimum 20)',
    detailedDescriptionOptional: 'Detailed description (optional)',
    detailedDescriptionPlaceholder: 'Add more details about your experience, specific services, etc.',
    
    // Onboarding - Location Step
    indicateMainLocation: 'Indicate your main location and work area. Clients will be able to find you in these areas.',
    province: 'Province',
    selectYourProvince: 'Select your province',
    city: 'City',
    locality: 'Locality',
    selectFromList: '(select from list)',
    selectYourCity: 'Select your city',
    asMainCity: '(as main city)',
    onlyFromList: 'Can only select from the list. If your locality is not listed, choose the nearest city.',
    neighborhoodOptional: 'Neighborhood / District (optional - free text)',
    neighborhoodPlaceholder: 'E.g.: Downtown, Chamartín, Eixample...',
    specifyNeighborhood: 'Specify a neighborhood or specific area if you want to be more precise (optional)',
    yourMainLocation: 'Your main location:',
    serviceRadius: 'Service radius *',
    onlyMyZone: 'Only my area',
    cityAndSurroundings: 'City & surroundings',
    metropolitanArea: 'Metropolitan area',
    provinceWide: 'Province',
    multipleProvinces: 'Multiple provinces',
    howFarTravel: 'How far are you willing to travel?',
    availability: 'Availability',
    whenCanYouWork: 'When can you work?',
    weekdays: 'Weekdays (Monday–Friday)',
    workMondayFriday: 'Work Monday to Friday',
    weekendsAndHolidays: 'Weekends and holidays',
    workWeekendsHolidays: 'Work Saturdays, Sundays and holidays',
    allWeek: 'Both (All week)',
    availableAnyDay: 'Available any day of the week',
    startTime: 'Start time *',
    endTime: 'End time *',
    schedulePreview: 'Schedule',
    
    // Onboarding - Pricing Step
    baseRateOptional: 'Base rate (€/hour or per service) - OPTIONAL',
    baseRatePlaceholder: 'E.g.: 35 (leave empty if you prefer not to show rate)',
    emptyNoRate: 'If you leave it empty, no rate information will be shown on your profile',
    invoiceType: 'Invoice type *',
    freelancer: 'Freelancer',
    company: 'Company',
    other: 'Other',
    acceptedPaymentMethods: 'Accepted payment methods *',
    selectAtLeastOnePayment: 'Select at least one payment method',
    card: 'Card',
    transfer: 'Bank transfer',
    cash: 'Cash',
    bizum: 'Bizum',
    selectedPayment: 'Selected',
    paymentMethodsSelected: 'payment method(s) selected',
    
    // Onboarding - Portfolio Step
    workPhotos: 'Work photos *',
    minimum1Photo: '(minimum 1)',
    clickToAddPhoto: 'Click to add a photo',
    photo: 'Photo',
    photosUploaded: 'photo(s) uploaded',
    mainPhoto: 'Main',
    
    // Onboarding - Legal Step
    readAndAcceptConsents: 'Read and accept the necessary consents to publish your profile',
    acceptAllConsents: 'Accept all consents',
    allConsentsAccepted: 'All consents accepted',
    termsAndConditionsLabel: 'Terms and Conditions',
    acceptTermsAndConditions: 'I have read and accept the',
    termsAndConditions: 'Terms and Conditions',
    ofPlatformUse: 'of use of the MisAutónomos platform.',
    privacyPolicyLabel: 'Privacy Policy',
    acceptPrivacyPolicy: 'I accept the',
    privacyPolicy: 'Privacy Policy',
    andDataTreatment: 'and the processing of my personal data according to GDPR.',
    contactConsentLabel: 'Contact Consent',
    consentClientContact: 'I consent to clients being able to contact me through the platform to request quotes and services.',
    
    // Onboarding - Review Step
    reviewAllInfo: 'Review all your information before publishing your professional profile. You can edit it later from your user panel.',
    edit: 'Edit',
    name: 'Name',
    nif: 'Tax ID',
    contactMethods: 'Contact methods',
    internalChatMethod: 'Internal Chat',
    whatsappMethod: 'WhatsApp',
    phoneCallMethod: 'Phone Call',
    none: 'None',
    notSpecified: 'Not specified',
    specificService: 'Specific service',
    description: 'Description',
    noDescription: 'No description',
    locationAndAvailability: 'Location and Availability',
    neighborhood: 'Neighborhood',
    availabilityColon: 'Availability:',
    scheduleColon: 'Schedule:',
    ratesAndWorkMethod: 'Rates and Work Method',
    baseRate: 'Base rate',
    invoicingType: 'Invoice type',
    paymentMethods: 'Payment methods',
    photos: 'Photos',
    legalConfirmations: 'Legal confirmations',
    acceptTerms: 'I accept the terms and conditions',
    acceptPrivacy: 'I accept the privacy policy',
    consentContact: 'I consent to being contacted by clients',
    
    // Onboarding - Success
    profileActiveTitle: 'Your professional profile is active!',
    visibleInSearches: 'You are now visible in',
    startReceivingContacts: 'Start receiving contacts from clients interested in your professional services.',
    profileActive: 'Profile active',
    visibleInSearch: 'Visible in searches',
    readyForClients: 'Ready for clients',
    viewMyPublicProfile: 'View my public profile',
    viewClientSearches: 'View client searches',
    editMyProfile: 'Edit my profile',
    tipsToStandOut: 'Tips to stand out',
    addMorePhotos: 'Keep your profile updated with recent photos of your work',
    respondFast: 'Respond quickly to messages to improve your search ranking',
    askForReviews: 'Ask satisfied clients for reviews',
    needHelp: 'Need help? Contact support:',
    restrictedAccess: 'Restricted access',
    professionalOnlyPage: 'This page is only for professionals. If you want to offer your services, you must first select a plan.',
    viewAvailablePlans: 'View available plans',
    
    // Validation errors
    professionalNameMinChars: 'Professional name must be at least 2 characters',
    cifNifMinChars: 'Tax ID must be at least 8 characters',
    invalidEmail: 'Invalid email',
    selectAtLeastOneContactMethod: 'Select at least one contact method',
    selectAtLeastOneCategory: 'Select at least one category',
    specifyServiceIfOther: 'Specify your service when selecting "Other professional service"',
    serviceSpecMinChars: 'Service specification must be at least 3 characters',
    shortDescriptionMinChars: 'Short description must be at least 20 characters',
    selectProvince: 'Select a province',
    selectCity: 'Select a city',
    selectAvailabilityType: 'Select an availability type',
    selectAtLeastOnePaymentMethod: 'Select at least one payment method',
    uploadAtLeast1Photo: 'Upload at least 1 photo of your work',
    acceptTermsAndConditionsError: 'You must accept the Terms and Conditions',
    acceptPrivacyPolicyError: 'You must accept the Privacy Policy',
    consentClientContactError: 'You must consent to being contacted by clients',
    errorSavingStep: 'Error saving: ',
    pleaseVerifyData: '. Please verify the data.',
    completeStep: 'Complete step',
    beforePublishing: 'before publishing',
    errorSavingProfile: 'Error saving profile',
    profileCompletedAndPublished: 'Profile completed and published successfully!',
    photoUploadSuccess: '✅ Photo uploaded successfully',
    photoUploadError: '❌ Error uploading photo',
    terms: 'terms',
    privacy: 'privacy',
    
    // Client Onboarding
    createClientAccount: 'Create your client account',
    completeDataToSearch: 'Complete this data to start searching for professionals',
    freeNoHiddenCosts: '100% FREE - No hidden costs',
    emailVerificationSent: 'Upon submission, we will create your account and you will receive a verification email from MisAutónomos',
    fullName: 'Full name',
    fullNamePlaceholder: 'E.g.: John Smith',
    emailCantChange: 'Your account email (cannot be changed here)',
    emailVerificationInfo: 'You will receive a verification email from MisAutónomos at this address',
    whatServicesLooking: 'What type of services are you looking for? *',
    createMyClientAccount: 'Create my client account',
    completeRegistration: 'Complete registration',
    redirectingToRegistration: 'Redirecting to registration...',
    savingYourData: 'We are saving your data and preparing your account.',
    redirectInSeconds: 'You will be redirected to the registration system in a few seconds...',
    alreadyProfessionalAccount: 'You already have a professional account',
    cantCreateClientAccount: 'Your account is already set up as a professional. You cannot create a client account simultaneously.',
    redirectingToProfile: 'Redirecting to your profile...',
    freeBenefit: '100% Free',
    noHiddenCosts: 'No hidden costs',
    verifiedProfessionals: 'Verified professionals',
    realReviews: 'With real reviews',
    directChat: 'Direct chat',
    immediateContact: 'Immediate contact',
    redirecting: 'Redirecting...',
    creatingAccount: 'Creating your account...',
    freeForClients: 'Upon completing registration, you will be able to search and contact professionals for free',
    
    // Subscription Management
    manageProfessionalPlan: 'Manage your professional plan',
    backToProfile: 'Back to My Profile',
    noActiveSubscription: 'No active subscription',
    needPlanToAppear: 'You need to hire a professional plan for your profile to appear in searches and receive client contacts.',
    verifyPaymentAdmin: 'Verify payment (Admin)',
    verifying: 'Verifying...',
    yourPlanInfo: 'Your plan information',
    currentPlan: 'Current plan',
    active: 'Active',
    canceled: 'Canceled',
    finished: 'Finished',
    trial: 'Trial',
    startDate: 'Start date',
    renewalExpiration: 'Renewal / Expiration',
    days: 'days',
    profileVisibleOk: 'Your profile is visible to all clients. Everything is in order.',
    trialActive: 'Active trial period. Your profile is visible to clients.',
    daysRemainingTrial: 'days remaining of free trial. If you do not cancel before the indicated date, automatic billing will occur.',
    subscriptionCanceledActive: 'Subscription canceled. Your plan is active until',
    profileVisibleFor: 'Your profile will remain visible for',
    moreDays: 'more days.',
    subscriptionFinishedHidden: 'Subscription finished. Your profile is no longer visible.',
    considerReactivating: 'Consider reactivating your plan to appear in searches again.',
    upgradeYourPlan: 'Upgrade your plan',
    saveUpTo: 'Save up to €138/year by switching to quarterly or annual plan',
    viewSuperiorPlans: 'View superior plans',
    reactivateYourPlan: 'Reactivate your plan',
    appearInSearches: 'Appear in searches again and receive new clients',
    cancelSubscription: 'Cancel subscription',
    cancelTrialNoCharge: 'If you cancel during trial, you will not be charged. Your profile will stop appearing immediately.',
    cancelHideProfile: 'Your profile will stop appearing in searches immediately, but you will retain access until the expiration date.',
    changePlan: 'Change plan',
    exploreOtherPlans: 'Explore other plans that better suit your needs',
    viewAllPlans: 'View all plans',
    confirmCancelSubscription: 'Cancel subscription?',
    ifYouCancel: 'If you cancel your subscription:',
    noChargeTrialCanceled: 'You will NOT be charged (your free trial is canceled)',
    profileHidesImmediately: 'Your profile will stop appearing immediately',
    canReactivateAnytime: 'You can reactivate at any time with another plan',
    profileHidesFromSearch: 'will stop appearing in searches immediately',
    noNewClientContacts: 'You will not receive new client contacts',
    accessUntil: 'You will retain access to your account until',
    canReactivateSubscription: 'You can reactivate your subscription at any time',
    areYouSureContinue: 'Are you sure you want to continue?',
    noKeepActive: 'No, keep active',
    canceling: 'Canceling...',
    yesCancelSubscription: 'Yes, cancel subscription',
    
    // Reviews
    reviewsTitle: 'Client reviews',
    noReviewsYet: 'No reviews yet',
    beFirstReview: 'Be the first to leave a review',
    speed: 'Speed',
    communication: 'Communication',
    quality: 'Quality',
    priceSatisfaction: 'Price/Satisfaction',
    reportReview: 'Report review',
    inappropriate: 'Inappropriate content',
    
    // Messages
    conversations: 'Conversations',
    noConversations: 'No conversations',
    startChatting: 'Start chatting with professionals',
    writeMessage: 'Write a message...',
    send: 'Send',
    loadingMessages: 'Loading messages...',
    user: 'User',
    you: 'You',
    professional: 'Professional',
    client: 'Client',
    online: 'Online',
    selectConversation: 'Select a conversation',
    chooseContactToChat: 'Choose a contact to start chatting',
    enterToSend: 'Press Enter to send, Shift+Enter for new line',
    messageSent: 'Message sent',
    sendMessageError: 'Error sending message',
    prepareMessageError: 'Error preparing message: ',
    
    // Review Dialog
    rateServiceOf: 'Rate service from',
    reviewHelpfulDescription: 'Your review helps other clients make informed decisions',
    rapidez: 'Speed',
    comunicacion: 'Communication',
    calidadTrabajo: 'Work quality',
    relacionCalidadPrecio: 'Value for money',
    tellExperienceOptional: 'Tell us about your experience (optional)',
    experiencePlaceholder: 'Describe your experience with this professional...',
    tip: 'Tip',
    honestReviewsHelpful: 'Honest reviews are the most helpful for the community',
    warning: 'Warning',
    alreadyReviewedMessage: 'You have already reviewed this professional',
    rateAllAspects: 'Please rate all aspects',
    commentMinLength: 'Comment must be at least 10 characters',
    reviewSuccess: 'Review published successfully',
    alreadyReviewed: 'Already reviewed',
    reviewError: 'Error publishing review',
    alreadyReviewedInfo: 'You have already reviewed this professional',
    bidirectionalConversationRequired: 'You can only review after receiving a response',
    cannotLeaveReviewNow: 'Cannot leave a review now',
    sending: 'Sending...',
    publishReview: 'Publish review',
    noMessagesInConversation: 'No messages in this conversation',
    contactProfessionalToStart: 'Contact a professional to start',
    loadingMessaging: 'Loading messages...',
    messagesPageDescription: 'Manage your conversations with professionals',
    
    // Favorites
    myFavorites: 'My Favorites',
    noFavorites: 'No favorites yet',
    addFavorites: 'Save your preferred professionals here',
    remove: 'Remove',
    
    // Footer
    tagline: 'Your trusted professional',
    platformDescription: 'Connecting professionals with clients across Spain',
    forProfessionals: 'For Professionals',
    forClients: 'For Clients',
    navigation: 'Navigation',
    legal: 'Legal',
    plansAndPricing: 'Plans & Pricing',
    createProfile: 'Create profile',
    joinAdvantages: 'Join advantages',
    helpCenter: 'Help center',
    createFreeAccount: 'Create free account',
    faq: 'FAQ',
    cookiePolicy: 'Cookie Policy',
    legalNotice: 'Legal Notice',
    allRightsReserved: 'All rights reserved',
    
    // Cookies Banner - NEW
    cookiesBannerTitle: 'This website uses cookies',
    cookiesBannerDescription: 'We use our own and third-party cookies to improve your browsing experience and the operation of the site. By clicking "Accept all", you accept the use of all cookies. You can manage your preferences in "Configure cookies".',
    acceptAllCookies: 'Accept all',
    acceptEssentialCookies: 'Only essential',
    configureCookies: 'Configure cookies',
    rejectAllCookies: 'Reject all',
    cookiePreferences: 'Cookie preferences',
    cookiePreferencesDescription: 'Manage which cookies you want to allow on MisAutónomos',
    essentialCookies: 'Essential cookies',
    essentialCookiesDescription: 'Necessary for the basic functioning of the website (authentication, security, navigation). Cannot be disabled.',
    analyticsCookies: 'Analytical cookies',
    analyticsCookiesDescription: 'Help us understand how users interact with the website to improve the experience (Google Analytics).',
    marketingCookies: 'Marketing cookies',
    marketingCookiesDescription: 'Used to display relevant advertising and measure the effectiveness of our advertising campaigns.',
    savePreferences: 'Save preferences',
    learnMoreCookies: 'More information:',
    
    // Tickets
    supportTickets: 'Support Tickets',
    myTickets: 'My Tickets',
    openTicket: 'Open Ticket',

    // Pricing Plans
    startFreeToday: 'Start free today',
    twoMonthsFree: '2 MONTHS FREE',
    noCommitment: 'No commitment',
    cancelAnytime: 'Cancel anytime',
    securePayment: '100% secure payment',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    annual: 'Annual',
    firstTwoMonths: 'first 2 months',
    then: 'Then',
    perMonth: '/month',
    every3Months: 'every 3 months',
    perYear: '/year',
    save10: '💰 Save 10% - Only €30/month',
    save20: '🎉 Save 20% - Only €26/month',
    mostPopular: 'Most popular',
    bestValue: 'Best value',
    appearInSearches: 'Appear in searches',
    directChatWithClients: 'Direct chat with clients',
    completeCRM: 'Complete CRM for clients',
    invoicingSystem: 'Invoicing system',
    integratedPaymentGateway: 'Integrated payment gateway',
    support247: '24/7 support via tickets',
    ratingsSystem: 'Ratings system',
    unlimitedPhotoGallery: 'Unlimited photo gallery',
    jobManagement: 'Job management',
    startNow: 'Start now',
    clickGoToCheckout: 'By clicking, you will go to the secure Stripe checkout',
    whatHappensAfter2Months: 'What happens after 2 months?',
    autoChargeExplain: 'It will be charged automatically according to the chosen plan. You can cancel before at no cost.',
    canCancelAnytime: 'Can I cancel anytime?',
    noPermanenceExplain: 'Yes, no commitment. Cancel before 60 days and pay nothing.',
    noPlansAvailable: 'No plans available',
    plansBeingConfigured: 'Plans are being configured. Please try again in a few minutes.',
    reloadPage: 'Reload page',
    
    // MyProfile
    myProfile: 'My Profile',
    manageYourProfile: 'Manage your professional profile',
    manageYourInformation: 'Manage your information',
    visibleToClients: 'Visible to clients',
    hiddenProfile: 'Hidden profile',
    personalInformation: 'Personal Information',
    professionalProfile: 'Professional Profile',
    portfolio: 'Portfolio',
    professionalIdentity: 'Professional Identity',
    yearsExperience: 'Years of experience',
    emailContact: 'Contact email',
    phoneContact: 'Contact phone',
    ibanForInvoices: 'IBAN (to receive invoice payments)',
    ibanHelp: 'Required to receive payments for invoices processed by MisAutónomos (transfer in 7 days)',
    servicesAndDescription: 'Services and Description',
    serviceCategory: 'Service category (choose only one)',
    servicesDescription: 'Description of your services',
    editProfile: 'Edit Profile',
    profileSaved: 'Profile saved successfully',
    errorSaving: 'Error saving',
    uploadingPhoto: 'Uploading photo...',
    profileUpdated: 'Profile updated',
    fullNameLabel: 'Full name',
    accountType: 'Account type',
    manageAvailability: 'Manage availability',
    profileActiveVisible: 'Your profile is active and visible in searches. Clients can find you and contact you.',
    profilePausedHidden: 'Your profile is paused. You do not appear in searches while you take a break.',
    activeAndVisible: 'Active and visible profile',
    clientsCanSee: 'Clients can see you in searches and contact you',
    profilePaused: 'Profile paused',
    usefulIfBusy: 'Useful if you have a lot of work and cannot attend to new clients',
    professionalNameRequired: 'Professional name *',
    locationLabel: 'Location',
    selectProvincePlaceholder: 'Select province',
    selectCityPlaceholder: 'Select city',
    firstChooseProvince: 'First choose province',
    ratesAndPayments: 'Rates and Payments',
    baseRateOptionalLabel: 'Base rate (€/hour) - optional',
    acceptedPaymentMethodsLabel: 'Accepted payment methods',
    clickToAddPhotos: 'Click to add photos ({count}/10)',
    selectMultiple: 'You can select multiple at once',
    photoNumber: 'Photo {number}',
    mainPhotoLabel: 'Main',
    socialNetworksLabel: 'Social Networks',
    wantOfferServices: 'Want to offer your services?',
    becomeProfessionalAppear: 'Become a professional and appear in client searches',
    verifyingSubscription: 'Verifying your subscription',
    confirmingPayment: 'We are confirming your payment and activating your account...',
    takesSeconds: 'This will only take a few seconds',
    dontCloseWindow: 'Please do not close this window while we process your payment.',
    trialPeriod: 'Trial period',
    trialEnded: 'Trial ended',
    daysTrialRemaining: '{days} trial days remaining',
    activeSubscription: 'Active subscription',
    renewal: 'Renewal',
    canceledSubscription: 'Subscription canceled',
    finishedSubscription: 'Subscription finished',
    activeUntil: 'Active until {date} (will not renew)',
    profileHidden: 'Your profile is hidden',
    inactiveSubscription: 'Inactive subscription',
    validUntil: 'Valid until {date}',
    reactivateToAppear: 'Reactivate your plan to appear in searches',
    personalDataUpdated: '✅ Personal data updated',
    professionalProfileUpdated: '✅ Professional profile updated',
    profileUpdatedSuccess: '✅ Your profile has been updated successfully.',
    profileNowVisible: '✅ Your profile is now visible in searches',
    profileNowHidden: '🔒 Your profile is hidden in searches',
    photosAdded: '✅ {count} photo(s) added',
    photoRemoved: 'Photo removed',
    errorUploadingPhotos: 'Error uploading photos',
    errorRemovingPhoto: 'Error removing photo',
    exceedsSize: '{filename} exceeds 5MB',
    noCategory: 'No category',
    saveChanges: 'Save changes',
    saving: 'Saving...',
    
    // ProfessionalProfile  
    backToSearch: 'Back to search',
    workGalleryTitle: 'Work gallery',
    socialNetworks: 'Social networks',
    statistics30Days: 'Statistics (30 days)',
    views: 'Views',
    searches: 'Searches',
    contacts: 'Contacts',
    clientReviews: 'Client reviews',
    
    // Common
    loading: 'Loading...',
    loadingProfessionals: 'Loading professionals...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    previous: 'Previous',
    confirm: 'Confirm',
    close: 'Close',
    search: 'Search',
    searchPlaceholder: 'E.g: plumber in Málaga, office cleaning…',
    allCategories: 'All categories',
    allProvinces: 'All provinces',
    allCities: 'All cities',
    results: 'results',
    professionalSingular: 'professional',
    professionalPlural: 'professionals',
    noResultsFound: 'No results found',
    tryDifferentLocation: 'Try different filters or search in another location',
    areYouProfessionalHere: 'Are you a professional in this area?',
    joinFreeAppearHere: 'Join for free and appear here. Start receiving clients today.',
    registerAsProfessional: 'Register as a professional',
    getMoreClients: 'Register for free and appear here. Get more clients today.',
    unread: 'unread',
    removedFromFavorites: 'Removed from favorites',
    addedToFavorites: 'Added to favorites',
    errorFavorites: 'Error managing favorites',
    processing: 'Processing...',
    paymentCanceled: 'Payment canceled. No worries, you can come back anytime.',
    noPhotosAdded: 'No photos added',
    profileNotFound: 'Profile not found',
    profileNotFoundDescription: 'The profile you are looking for does not exist or has been deleted.',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('es');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') || 'es';
    setLanguage(savedLang);
    document.documentElement.lang = savedLang;
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations.es[key] || key;
    
    Object.keys(params).forEach(param => {
      text = text.replace(`{{${param}}}`, params[param]);
    });
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export default function LanguageSwitcher({ variant = "default" }) {
  const { language, changeLanguage } = useLanguage();

  if (variant === "compact") {
    return (
      <div className="flex gap-1 bg-gray-100 rounded-lg p-1">
        <button
          onClick={() => changeLanguage('es')}
          className={`px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
            language === 'es'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'text-gray-600 hover:bg-gray-200'
          }`}
          aria-label="Cambiar idioma a Español"
        >
          ES
        </button>
        <button
          onClick={() => changeLanguage('en')}
          className={`px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
            language === 'en'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'text-gray-600 hover:bg-gray-200'
          }`}
          aria-label="Change language to English"
        >
          EN
        </button>
      </div>
    );
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="hover:bg-gray-100" aria-label="Cambiar idioma">
          <Globe className="h-5 w-5 text-gray-600" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="bg-white">
        <DropdownMenuItem
          onClick={() => changeLanguage('es')}
          className={language === 'es' ? 'bg-blue-50 text-blue-900 font-semibold' : ''}
        >
          🇪🇸 Español
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => changeLanguage('en')}
          className={language === 'en' ? 'bg-blue-50 text-blue-900 font-semibold' : ''}
        >
          🇬🇧 English
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}