import React, { createContext, useContext, useState, useEffect } from 'react';
import { Globe } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

const translations = {
  es: {
    // Navigation
    searchFreelancers: 'Buscar Autónomos',
    messages: 'Mensajes',
    favorites: 'Favoritos',
    myProfile: 'Mi Perfil',
    mySubscription: 'Mi Suscripción',
    administration: 'Administración',
    viewPlans: 'Ver Planes',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
    becomeFreelancer: 'Hazte autónomo',
    back: 'Volver',
    contact: 'Contacto',
    
    // Hero
    heroTitle: 'Encuentra tu autónomo de confianza',
    heroSubtitle: 'Conecta con profesionales verificados cerca de ti. Rápido, fácil y seguro.',
    chooseHow: '¿Cómo quieres usar MisAutónomos?',
    imFreelancer: 'Soy autónomo',
    imClient: 'Busco servicios',
    
    // Search
    filters: 'Filtros de búsqueda',
    search: 'Buscar servicio, empresa...',
    allCategories: 'Todas las categorías',
    allProvinces: 'Todas las provincias',
    allCities: 'Todas las ciudades',
    freelancersAvailable: 'autónomos disponibles',
    verifiedProfessionals: 'Profesionales verificados',
    noResults: 'No se encontraron resultados',
    tryDifferentFilters: 'Intenta con otros filtros o busca en otra ubicación',
    viewAll: 'Ver todos',
    discoverFreelancers: 'Descubrir autónomos',
    
    // Categories
    'Electricista': 'Electricista',
    'Fontanero': 'Fontanero',
    'Carpintero': 'Carpintero',
    'Albañil / Reformas': 'Albañil / Reformas',
    'Pintor': 'Pintor',
    'Jardinero': 'Jardinero',
    'Transportista': 'Transportista',
    'Autónomo de limpieza': 'Autónomo de limpieza',
    'Cerrajero': 'Cerrajero',
    'Instalador de aire acondicionado': 'Instalador de aire acondicionado',
    'Mantenimiento general': 'Mantenimiento general',
    'Asesoría o gestoría': 'Asesoría o gestoría',
    'Empresa multiservicios': 'Empresa multiservicios',
    'Otro tipo de servicio profesional': 'Otro tipo de servicio',
    
    // Cards & Profile
    verified: 'Verificado',
    availableNow: 'Disponible ahora',
    until: 'Hasta las',
    call: 'Llamar',
    whatsapp: 'WhatsApp',
    chat: 'Chat directo',
    workArea: 'Zona de trabajo',
    hourRate: 'Tarifa media',
    noOpinions: 'Sin opiniones aún',
    workGallery: 'Galería de Trabajos',
    reviews: 'opiniones',
    review: 'opinión',
    information: 'Información',
    schedule: 'Horario',
    mondayFriday: 'Lunes a Viernes',
    weekends: 'Sábados, domingos y festivos',
    everyday: 'Todos los días',
    averageRate: 'Tarifa media',
    email: 'Email',
    phone: 'Teléfono',
    website: 'Sitio web',
    visitWebsite: 'Visitar sitio web',
    
    // Profile Completeness
    profileCompleteness: 'Completitud del perfil',
    completeProfileForMore: 'Completa tu perfil para recibir más clientes',
    goodProgress: 'Buen progreso, añade más detalles',
    almostPerfect: '¡Casi perfecto! Solo faltan algunos detalles',
    addTheseElements: 'Añade estos elementos para mejorar tu perfil:',
    completeNow: 'Completar ahora',
    professionalName: 'Nombre profesional',
    profilePicture: 'Foto de perfil',
    cifNif: 'NIF/CIF',
    telephoneContact: 'Teléfono',
    shortDescription: 'Descripción corta',
    categoryPlural: 'Categorías',
    photoGallery: 'Galería de fotos',
    location: 'Ubicación',
    paymentMethods: 'Formas de pago',
    
    // Onboarding - Steps
    completeYourProfile: 'Completa tu perfil profesional',
    step: 'Paso',
    of: 'de',
    identity: 'Identidad',
    activity: 'Actividad',
    zoneAndAvailability: 'Zona y disponibilidad',
    pricesAndWorkMethod: 'Precios y forma de trabajo',
    portfolioPhotos: 'Portfolio (fotos)',
    consentsAndLegal: 'Consentimientos y Legales',
    finalReview: 'Revisión final',
    next: 'Siguiente',
    saving: 'Guardando...',
    publishing: 'Publicando...',
    publishProfile: 'Publicar perfil',
    
    // Onboarding - Identity Step
    professionalNameLabel: 'Nombre profesional *',
    professionalNamePlaceholder: 'Ej: Juan Pérez - Electricista',
    characters: 'caracteres',
    cifNifLabel: 'NIF / CIF *',
    cifNifPlaceholder: '12345678A o B12345678',
    contactEmailLabel: 'Email de contacto *',
    contactEmailPlaceholder: 'tu@email.com',
    contactPhoneOptional: 'Teléfono de contacto (opcional)',
    contactPhonePlaceholder: '612345678 o +34612345678',
    noPhoneOnlyChat: 'Si no añades teléfono, solo podrán contactarte por chat interno',
    visibleContactMethods: 'Métodos de contacto visibles',
    selectHowClientsContact: 'Selecciona cómo quieres que los clientes te contacten',
    internalChat: 'Chat interno',
    alwaysActive: 'Siempre activo (obligatorio)',
    phoneCall: 'Llamada telefónica',
    requiresPhone: 'Requiere teléfono',
    addPhoneFirstWhatsApp: 'Añade un teléfono primero para activar WhatsApp',
    addPhoneFirstCall: 'Añade un teléfono primero para activar las llamadas',
    
    // Onboarding - Activity Step
    serviceCategories: 'Categorías de servicio *',
    selectAtLeastOne: '(selecciona al menos una)',
    selected: 'seleccionada',
    selectedPlural: 'seleccionadas',
    specifyYourService: 'Especifica tu servicio *',
    specifyServicePlaceholder: 'Ej: Instalador de paneles solares, Técnico de fibra óptica, etc.',
    describeYourActivity: 'Describe tu actividad profesional (mínimo 3 caracteres)',
    shortDescriptionLabel: 'Descripción corta *',
    shortDescriptionMax: '(máximo 220 caracteres)',
    shortDescriptionPlaceholder: 'Describe brevemente tus servicios...',
    minimum20: '(mínimo 20)',
    detailedDescriptionOptional: 'Descripción detallada (opcional)',
    detailedDescriptionPlaceholder: 'Añade más detalles sobre tu experiencia, servicios específicos, etc.',
    
    // Onboarding - Location Step
    indicateMainLocation: 'Indica tu ubicación principal y zona de trabajo. Los clientes podrán encontrarte en estas áreas.',
    province: 'Provincia',
    selectYourProvince: 'Selecciona tu provincia',
    city: 'Ciudad',
    locality: 'Localidad',
    selectFromList: '(selecciona de la lista)',
    selectYourCity: 'Selecciona tu ciudad',
    asMainCity: '(como ciudad principal)',
    onlyFromList: 'Solo se puede seleccionar de la lista. Si tu localidad no aparece, elige la ciudad más cercana.',
    neighborhoodOptional: 'Barrio / Municipio (opcional - texto libre)',
    neighborhoodPlaceholder: 'Ej: Centro, Chamartín, Eixample...',
    specifyNeighborhood: 'Especifica un barrio o zona específica si quieres ser más preciso (opcional)',
    yourMainLocation: 'Tu ubicación principal:',
    serviceRadius: 'Radio de servicio *',
    onlyMyZone: 'Solo mi zona',
    cityAndSurroundings: 'Ciudad y alrededores',
    metropolitanArea: 'Área metropolitana',
    provinceWide: 'Provincia',
    multipleProvinces: 'Múltiples provincias',
    howFarTravel: '¿Hasta qué distancia estás dispuesto a desplazarte?',
    availability: 'Disponibilidad',
    whenCanYouWork: '¿Cuándo puedes trabajar?',
    weekdays: 'Días laborables (Lunes–Viernes)',
    workMondayFriday: 'Trabajo de lunes a viernes',
    weekendsAndHolidays: 'Fines de semana y festivos',
    workWeekendsHolidays: 'Trabajo sábados, domingos y festivos',
    allWeek: 'Ambos (Toda la semana)',
    availableAnyDay: 'Disponible cualquier día de la semana',
    startTime: 'Hora de inicio *',
    endTime: 'Hora de fin *',
    schedulePreview: 'Horario',
    
    // Onboarding - Pricing Step
    baseRateOptional: 'Tarifa base (€/hora o por servicio) - OPCIONAL',
    baseRatePlaceholder: 'Ej: 35 (déjalo vacío si prefieres no mostrar tarifa)',
    emptyNoRate: 'Si lo dejas vacío, no se mostrará información de tarifa en tu perfil',
    invoiceType: 'Tipo de facturación *',
    freelancer: 'Autónomo',
    company: 'Sociedad',
    other: 'Otros',
    acceptedPaymentMethods: 'Formas de pago aceptadas *',
    selectAtLeastOnePayment: 'Selecciona al menos una forma de pago',
    card: 'Tarjeta',
    transfer: 'Transferencia',
    cash: 'Efectivo',
    bizum: 'Bizum',
    selectedPayment: 'Seleccionado',
    paymentMethodsSelected: 'forma(s) de pago seleccionada(s)',
    
    // Onboarding - Portfolio Step
    workPhotos: 'Fotos de trabajos realizados *',
    minimum1Photo: '(mínimo 1)',
    clickToAddPhoto: 'Haz clic para añadir una foto',
    photo: 'Foto',
    photosUploaded: 'foto(s) subida(s)',
    mainPhoto: 'Principal',
    
    // Onboarding - Legal Step
    readAndAcceptConsents: 'Lee y acepta los consentimientos necesarios para publicar tu perfil',
    acceptAllConsents: 'Aceptar todos los consentimientos',
    allConsentsAccepted: 'Todos los consentimientos aceptados',
    termsAndConditionsLabel: 'Términos y Condiciones',
    acceptTermsAndConditions: 'He leído y acepto los',
    termsAndConditions: 'Términos y Condiciones',
    ofPlatformUse: 'de uso de la plataforma MisAutónomos.',
    privacyPolicyLabel: 'Política de Privacidad',
    acceptPrivacyPolicy: 'Acepto la',
    privacyPolicy: 'Política de Privacidad',
    andDataTreatment: 'y el tratamiento de mis datos personales según el RGPD.',
    contactConsentLabel: 'Consentimiento de Contacto',
    consentClientContact: 'Consiento en que los clientes puedan contactarme a través de la plataforma para solicitar presupuestos y servicios.',
    
    // Onboarding - Review Step
    reviewAllInfo: 'Revisa toda tu información antes de publicar tu perfil profesional. Podrás editarla después desde tu panel de usuario.',
    edit: 'Editar',
    name: 'Nombre',
    nif: 'NIF',
    contactMethods: 'Métodos de contacto',
    internalChatMethod: 'Chat Interno',
    whatsappMethod: 'WhatsApp',
    phoneCallMethod: 'Llamada Telefónica',
    none: 'Ninguno',
    notSpecified: 'No especificado',
    specificService: 'Servicio específico',
    description: 'Descripción',
    noDescription: 'Sin descripción',
    locationAndAvailability: 'Ubicación y Disponibilidad',
    neighborhood: 'Municipio',
    availabilityColon: 'Disponibilidad:',
    scheduleColon: 'Horario:',
    ratesAndWorkMethod: 'Tarifas y Forma de Trabajo',
    baseRate: 'Tarifa base',
    invoicingType: 'Tipo de facturación',
    paymentMethods: 'Formas de pago',
    photos: 'Fotos',
    noPhotosAdded: 'Sin fotos añadidas',
    legalConfirmations: 'Confirmaciones legales',
    acceptTerms: 'Acepto los términos y condiciones',
    acceptPrivacy: 'Acepto la política de privacidad',
    consentContact: 'Consiento ser contactado por clientes',
    
    // Onboarding - Success
    profileActiveTitle: '¡Tu perfil profesional está activo!',
    visibleInSearches: 'Ya eres visible en las búsquedas de',
    startReceivingContacts: 'Empieza a recibir contactos de clientes interesados en tus servicios profesionales.',
    profileActive: 'Perfil activo',
    visibleInSearch: 'Visible en búsquedas',
    readyForClients: 'Listo para clientes',
    viewMyPublicProfile: 'Ver mi ficha pública',
    viewClientSearches: 'Ver búsquedas de clientes',
    editMyProfile: 'Editar mi perfil',
    tipsToStandOut: 'Consejos para destacar',
    addMorePhotos: 'Mantén tu perfil actualizado con fotos recientes de tus trabajos',
    respondFast: 'Responde rápido a los mensajes para mejorar tu posición en búsquedas',
    askForReviews: 'Pide valoraciones a tus clientes satisfechos',
    needHelp: '¿Necesitas ayuda? Contacta con soporte:',
    restrictedAccess: 'Acceso restringido',
    professionalOnlyPage: 'Esta página es solo para profesionales. Si deseas ofrecer tus servicios, primero debes seleccionar un plan.',
    viewAvailablePlans: 'Ver planes disponibles',
    
    // Validation errors
    professionalNameMinChars: 'El nombre profesional debe tener al menos 2 caracteres',
    cifNifMinChars: 'El NIF/CIF debe tener al menos 8 caracteres',
    invalidEmail: 'Email inválido',
    selectAtLeastOneContactMethod: 'Selecciona al menos un método de contacto',
    selectAtLeastOneCategory: 'Selecciona al menos una categoría',
    specifyServiceIfOther: 'Especifica tu servicio cuando seleccionas "Otro tipo de servicio profesional"',
    serviceSpecMinChars: 'La especificación del servicio debe tener al menos 3 caracteres',
    shortDescriptionMinChars: 'La descripción corta debe tener al menos 20 caracteres',
    selectProvince: 'Selecciona una provincia',
    selectCity: 'Selecciona una ciudad',
    selectAvailabilityType: 'Selecciona un tipo de disponibilidad',
    selectAtLeastOnePaymentMethod: 'Selecciona al menos una forma de pago',
    uploadAtLeast1Photo: 'Sube al menos 1 foto de tus trabajos',
    acceptTermsAndConditionsError: 'Debes aceptar los Términos y Condiciones',
    acceptPrivacyPolicyError: 'Debes aceptar la Política de Privacidad',
    consentClientContactError: 'Debes consentir ser contactado por clientes',
    errorSavingStep: 'Error al guardar: ',
    pleaseVerifyData: '. Verifica los datos.',
    completeStep: 'Completa el paso',
    beforePublishing: 'antes de publicar',
    errorSavingProfile: 'Error al guardar el perfil',
    profileCompletedAndPublished: '¡Perfil completado y publicado con éxito!',
    photoUploadSuccess: '✅ Foto subida correctamente',
    photoUploadError: '❌ Error al subir la foto',
    terms: 'términos',
    privacy: 'privacidad',
    
    // Client Onboarding
    createClientAccount: 'Crea tu cuenta de cliente',
    completeDataToSearch: 'Completa estos datos para empezar a buscar profesionales',
    freeNoHiddenCosts: '100% GRATIS - Sin costes ocultos',
    emailVerificationSent: 'Al enviar, crearemos tu cuenta y recibirás un email de verificación de MisAutónomos',
    fullName: 'Nombre completo',
    fullNamePlaceholder: 'Ej: Juan Pérez',
    emailCantChange: 'Email de tu cuenta (no se puede cambiar aquí)',
    emailVerificationInfo: 'Recibirás un email de verificación de MisAutónomos en esta dirección',
    whatServicesLooking: '¿Qué tipo de servicios buscas? *',
    createMyClientAccount: 'Crear mi cuenta de cliente',
    completeRegistration: 'Completar registro',
    redirectingToRegistration: 'Redirigiendo al registro...',
    savingYourData: 'Estamos guardando tus datos y preparando tu cuenta.',
    redirectInSeconds: 'Serás redirigido al sistema de registro en unos segundos...',
    alreadyProfessionalAccount: 'Ya tienes una cuenta profesional',
    cantCreateClientAccount: 'Tu cuenta ya está configurada como autónomo. No puedes crear una cuenta de cliente simultáneamente.',
    redirectingToProfile: 'Redirigiendo a tu perfil...',
    freeBenefit: '100% Gratis',
    noHiddenCosts: 'Sin costes ocultos',
    realReviews: 'Con valoraciones reales',
    directChat: 'Chat directo',
    immediateContact: 'Contacto inmediato',
    redirecting: 'Redirigiendo...',
    creatingAccount: 'Creando tu cuenta...',
    freeForClients: 'Al completar el registro podrás buscar y contactar con profesionales de forma gratuita',
    
    // Subscription Management
    manageProfessionalPlan: 'Gestiona tu plan profesional',
    backToProfile: 'Volver a Mi Perfil',
    noActiveSubscription: 'Sin suscripción activa',
    needPlanToAppear: 'Necesitas contratar un plan profesional para que tu perfil aparezca en las búsquedas y puedas recibir contactos de clientes.',
    verifyPaymentAdmin: 'Verificar pago (Admin)',
    verifying: 'Verificando...',
    yourPlanInfo: 'Información de tu plan',
    currentPlan: 'Plan actual',
    active: 'Activo',
    canceled: 'Cancelado',
    finished: 'Finalizado',
    trial: 'Prueba',
    startDate: 'Fecha de inicio',
    renewalExpiration: 'Renovación / Expiración',
    days: 'días',
    profileVisibleOk: 'Tu perfil es visible para todos los clientes. Todo en orden.',
    trialActive: 'Periodo de prueba activa. Tu perfil es visible para clientes.',
    daysRemainingTrial: 'días restantes de prueba gratuita. Si no cancelas antes de la fecha indicada, se realizará el cobro automático.',
    subscriptionCanceledActive: 'Suscripción cancelada. Tu plan está activo hasta el',
    profileVisibleFor: 'Tu perfil seguirá visible durante',
    moreDays: 'días más.',
    subscriptionFinishedHidden: 'Suscripción finalizada. Tu perfil ya no es visible.',
    considerReactivating: 'Considera reactivar tu plan para volver a aparecer en las búsquedas.',
    upgradeYourPlan: 'Mejora tu plan',
    saveUpTo: 'Ahorra hasta 138€/año cambiando a plan trimestral o anual',
    viewSuperiorPlans: 'Ver planes superiores',
    reactivateYourPlan: 'Reactiva tu plan',
    appearInSearches: 'Vuelve a aparecer en las búsquedas y recibe nuevos clientes',
    cancelSubscription: 'Cancelar suscripción',
    cancelTrialNoCharge: 'Si cancelas durante la prueba, no se te cobrará nada. Tu perfil dejará de aparecer inmediatamente.',
    cancelHideProfile: 'Tu perfil dejará de aparecer en las búsquedas inmediatamente, pero seguirás teniendo acceso hasta la fecha de expiración.',
    changePlan: 'Cambiar plan',
    exploreOtherPlans: 'Explora otros planes que se adapten mejor a tus necesidades',
    viewAllPlans: 'Ver todos los planes',
    confirmCancelSubscription: '¿Cancelar suscripción?',
    ifYouCancel: 'Si cancelas tu suscripción:',
    noChargeTrialCanceled: 'NO se te cobrará nada (tu prueba gratuita se cancela)',
    profileHidesImmediately: 'Tu perfil dejará de aparecer inmediatamente',
    canReactivateAnytime: 'Puedes reactivar en cualquier momento con otro plan',
    profileHidesFromSearch: 'dejará de aparecer en las búsquedas inmediatamente',
    noNewClientContacts: 'No recibirás nuevos contactos de clientes',
    accessUntil: 'Mantendrás acceso a tu cuenta hasta el',
    canReactivateSubscription: 'Podrás reactivar tu suscripción en cualquier momento',
    areYouSureContinue: '¿Estás seguro que deseas continuar?',
    noKeepActive: 'No, mantener activo',
    canceling: 'Cancelando...',
    yesCancelSubscription: 'Sí, cancelar suscripción',
    
    // Reviews
    reviewsTitle: 'Opiniones de clientes',
    noReviewsYet: 'Sin opiniones por ahora',
    beFirstReview: 'Sé el primero en dejar una opinión',
    speed: 'Rapidez',
    communication: 'Comunicación',
    quality: 'Calidad',
    priceSatisfaction: 'Precio/Satisfacción',
    reportReview: 'Reportar opinión',
    inappropriate: 'Contenido inapropiado',
    
    // Messages
    conversations: 'Conversaciones',
    noConversations: 'No hay conversaciones',
    startChatting: 'Comienza a chatear con profesionales',
    writeMessage: 'Escribe un mensaje...',
    send: 'Enviar',
    loadingMessages: 'Cargando mensajes...',
    user: 'Usuario',
    you: 'Tú',
    professional: 'Autónomo',
    client: 'Cliente',
    online: 'En línea',
    selectConversation: 'Selecciona una conversación',
    chooseContactToChat: 'Elige un contacto para comenzar a chatear',
    enterToSend: 'Presiona Enter para enviar, Shift+Enter para nueva línea',
    messageSent: 'Mensaje enviado',
    sendMessageError: 'Error al enviar el mensaje',
    prepareMessageError: 'Error al preparar el mensaje: ',
    
    // Review Dialog
    rateServiceOf: 'Valorar el servicio de',
    reviewHelpfulDescription: 'Tu opinión ayuda a otros clientes a tomar decisiones informadas',
    rapidez: 'Rapidez',
    comunicacion: 'Comunicación',
    calidadTrabajo: 'Calidad del trabajo',
    relacionCalidadPrecio: 'Relación calidad/precio',
    tellExperienceOptional: 'Cuéntanos tu experiencia (opcional)',
    experiencePlaceholder: 'Describe tu experiencia con este profesional...',
    tip: 'Consejo',
    honestReviewsHelpful: 'Las valoraciones honestas son las más útiles para la comunidad',
    warning: 'Aviso',
    alreadyReviewedMessage: 'Ya has valorado a este profesional anteriormente',
    rateAllAspects: 'Por favor, valora todos los aspectos',
    commentMinLength: 'El comentario debe tener al menos 10 caracteres',
    reviewSuccess: 'Valoración publicada correctamente',
    alreadyReviewed: 'Ya has valorado este servicio',
    reviewError: 'Error al publicar la valoración',
    alreadyReviewedInfo: 'Ya has valorado a este profesional',
    bidirectionalConversationRequired: 'Solo puedes valorar después de recibir una respuesta',
    cannotLeaveReviewNow: 'No puedes dejar una valoración ahora',
    sending: 'Enviando...',
    publishReview: 'Publicar valoración',
    noMessagesInConversation: 'No hay mensajes en esta conversación',
    contactProfessionalToStart: 'Contacta con un profesional para empezar',
    loadingMessaging: 'Cargando mensajes...',
    messagesPageDescription: 'Gestiona tus conversaciones con profesionales',
    
    // Favorites
    myFavorites: 'Mis Favoritos',
    noFavorites: 'Aún no tienes favoritos',
    addFavorites: 'Guarda tus profesionales preferidos aquí',
    remove: 'Eliminar',
    
    // Footer
    tagline: 'Tu autónomo de confianza',
    platformDescription: 'Conectamos profesionales con clientes en toda España',
    forProfessionals: 'Para Profesionales',
    forClients: 'Para Clientes',
    navigation: 'Navegación',
    legal: 'Legal',
    plansAndPricing: 'Planes y precios',
    createProfile: 'Crear perfil',
    joinAdvantages: 'Ventajas de unirse',
    helpCenter: 'Centro de ayuda',
    createFreeAccount: 'Crear cuenta gratis',
    faq: 'Preguntas frecuentes',
    cookiePolicy: 'Política de cookies',
    legalNotice: 'Aviso legal',
    allRightsReserved: 'Todos los derechos reservados',
    
    // Cookies Banner
    cookiesBannerTitle: 'Este sitio web utiliza cookies',
    cookiesBannerDescription: 'Utilizamos cookies propias y de terceros para mejorar tu experiencia de navegación y el funcionamiento del sitio. Al hacer clic en "Aceptar todas", aceptas el uso de todas las cookies. Puedes gestionar tus preferencias en "Configurar cookies".',
    acceptAllCookies: 'Aceptar todas',
    acceptEssentialCookies: 'Solo esenciales',
    configureCookies: 'Configurar cookies',
    rejectAllCookies: 'Rechazar todas',
    cookiePreferences: 'Preferencias de cookies',
    cookiePreferencesDescription: 'Gestiona qué cookies quieres permitir en MisAutónomos',
    essentialCookies: 'Cookies esenciales',
    essentialCookiesDescription: 'Necesarias para el funcionamiento básico del sitio web (autenticación, seguridad, navegación). No se pueden desactivar.',
    analyticsCookies: 'Cookies analíticas',
    analyticsCookiesDescription: 'Nos ayudan a entender cómo interactúan los usuarios con la web para mejorar la experiencia (Google Analytics).',
    marketingCookies: 'Cookies de marketing',
    marketingCookiesDescription: 'Utilizadas para mostrar publicidad relevante y medir la efectividad de nuestras campañas publicitarias.',
    alwaysActive: 'Siempre activas',
    savePreferences: 'Guardar preferencias',
    learnMoreCookies: 'Más información:',
    
    // Common
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    previous: 'Anterior',
    confirm: 'Confirmar',
    close: 'Cerrar',
    
    // MyProfile page
    myProfileTitle: 'Mi Perfil',
    manageYourInfo: 'Gestiona tu información',
    manageProfessionalProfile: 'Gestiona tu perfil profesional',
    visibleToClients: 'Visible para clientes',
    profileHidden: 'Perfil oculto',
    editProfile: 'Editar Perfil',
    becomeProfessional: 'Hazte Autónomo',
    cancelEdit: 'Cancelar',
    saveChanges: 'Guardar cambios',
    savingChanges: 'Guardando...',
    profileUpdatedSuccess: 'Tu perfil se ha actualizado correctamente',
    wantToOfferServices: '¿Quieres ofrecer tus servicios?',
    becomeProfessionalAppear: 'Conviértete en autónomo y aparece en las búsquedas de clientes',
    viewPlansButton: 'Ver Planes',
    personalInfo: 'Información Personal',
    professionalProfile: 'Perfil Profesional',
    portfolio: 'Portfolio',
    personalInfoSection: 'Información personal',
    fullNameLabel: 'Nombre completo',
    phoneLabel: 'Teléfono',
    cityLabel: 'Ciudad',
    accountType: 'Tipo de cuenta',
    professionalAccount: 'Autónomo',
    clientAccount: 'Cliente',
    dangerZone: 'Zona de peligro',
    dangerZoneDescription: 'Esta acción eliminará permanentemente tu cuenta, perfil, mensajes, favoritos, reseñas y cancelará tu suscripción activa.',
    deleteMyAccount: 'Eliminar mi cuenta',
    
    // Professional Identity
    professionalIdentity: 'Identidad Profesional',
    professionalNameRequired: 'Nombre profesional *',
    professionalNamePlaceholder2: 'Tu Empresa S.L.',
    taxIdLabel: 'NIF/CIF',
    taxIdPlaceholder: '12345678A',
    yearsExperience: 'Años de experiencia',
    yearsPlaceholder: '5',
    contactEmailLabel2: 'Email de contacto',
    contactPhoneLabel: 'Teléfono de contacto',
    certificationsLabel: 'Certificaciones y títulos',
    certificationPlaceholder: 'Certificación profesional, título...',
    
    // Services & Description
    servicesDescription: 'Servicios y Descripción',
    serviceCategoriesLabel: 'Categorías de servicio',
    specifyService: 'Especifica tu servicio',
    specifyServicePlaceholder2: 'Instalador de paneles solares...',
    shortDescriptionLimit: 'Descripción corta (220 caracteres)',
    shortDescPlaceholder: 'Describe brevemente tus servicios...',
    detailedDescriptionSEO: 'Descripción detallada (para SEO)',
    detailedDescPlaceholder: 'Experiencia, especialidades, proyectos destacados...',
    
    // Location & Availability Section
    locationAvailability: 'Ubicación y Disponibilidad',
    provinceLabel: 'Provincia',
    selectProvincePlaceholder: 'Selecciona provincia',
    cityLabel2: 'Ciudad',
    cityPlaceholder: 'Madrid',
    neighborhoodLabel: 'Barrio / Municipio (opcional)',
    neighborhoodPlaceholder2: 'Centro, Chamartín...',
    serviceRadiusLabel: 'Radio de servicio',
    serviceRadius5: '5 km - Solo mi zona',
    serviceRadius10: '10 km - Ciudad',
    serviceRadius25: '25 km - Área metropolitana',
    serviceRadius50: '50 km - Provincia',
    serviceRadius100: '100+ km - Múltiples provincias',
    availabilityLabel: 'Disponibilidad',
    availabilityWeekdays: 'Días laborables (Lun-Vie)',
    availabilityWeekends: 'Fines de semana y festivos',
    availabilityAllWeek: 'Toda la semana',
    startTimeLabel: 'Hora de inicio',
    endTimeLabel: 'Hora de fin',
    
    // Rates & Work Method
    ratesWorkMethod: 'Tarifas y Forma de Trabajo',
    baseRateHourly: 'Tarifa base (€/hora) - opcional',
    baseRatePlaceholder2: '35',
    businessTypeLabel: 'Tipo de facturación',
    selfEmployed: 'Autónomo',
    limitedCompany: 'Sociedad',
    others: 'Otros',
    acceptedPaymentMethodsLabel: 'Formas de pago aceptadas',
    cardPayment: 'Tarjeta',
    bankTransfer: 'Transferencia',
    cashPayment: 'Efectivo',
    bizumPayment: 'Bizum',
    
    // Online Presence
    onlinePresence: 'Presencia Online',
    websiteLabel: 'Sitio web',
    websitePlaceholder: 'https://tuweb.com',
    facebookLabel: 'Facebook',
    facebookPlaceholder: 'https://facebook.com/tupagina',
    instagramLabel: 'Instagram',
    instagramPlaceholder: 'https://instagram.com/tuperfil',
    linkedinLabel: 'LinkedIn',
    linkedinPlaceholder: 'https://linkedin.com/in/tuperfil',
    tiktokLabel: 'TikTok',
    tiktokPlaceholder: 'https://tiktok.com/@tuperfil',
    
    // Work Gallery
    workGalleryTitle: 'Galería de Trabajos',
    workGalleryDescription: 'Sube fotos de tus trabajos realizados. Máximo 10 imágenes. La primera será tu foto principal.',
    clickToAddPhotoGallery: 'Haz clic para añadir foto ({{count}}/10)',
    photoAlt: 'Foto {{number}}',
    mainPhotoLabel: 'Principal',
    
    // Delete Account Dialog
    deleteAccountTitle: '¿Eliminar tu cuenta definitivamente?',
    deleteAccountWarning: 'ATENCIÓN: Esta acción es IRREVERSIBLE',
    willBeDeleted: 'Se eliminará permanentemente:',
    yourAccountProfile: 'Tu cuenta y perfil completo',
    allMessagesConversations: 'Todos tus mensajes y conversaciones',
    favoritesReviews: 'Tus favoritos y reseñas',
    professionalProfilePhotos: 'Tu perfil profesional y fotos',
    activeSubscription: 'Tu suscripción activa',
    cancelButton: 'Cancelar',
    deletingAccount: 'Eliminando...',
    yesDeletePermanently: 'Sí, eliminar definitivamente',
    accountDeleted: 'Tu cuenta ha sido eliminada correctamente',
    errorDeletingAccount: 'Error al eliminar tu cuenta',
    
    // Premium Dashboard
    premiumPanel: 'Panel Premium',
    enjoyPlanBenefits: 'Disfruta de todas las ventajas de tu plan',
    upgradePlanUnlock: 'Mejora tu plan para desbloquear todas las funciones',
    premium: 'Premium',
    profileViews30Days: 'Visitas al perfil (30 días)',
    perDay: 'por día',
    messagesReceived: 'Mensajes recibidos',
    last30Days: 'Últimos 30 días',
    searchAppearances: 'Apariciones en búsqueda',
    contactClicks: 'Clics en contacto',
    phoneWhatsAppEtc: 'Teléfono, WhatsApp, etc.',
    unlockStatistics: 'Desbloquea tus estadísticas',
    premiumPlanMetrics: 'Con un plan premium podrás ver todas tus métricas y optimizar tu perfil',
    viewPremiumPlans: 'Ver planes premium',
    profileCompletenessTitle: 'Completitud del perfil',
    percentComplete: '{{percentage}}% completo',
    excellent: '¡Excelente!',
    goodProgressStatus: 'Buen progreso',
    addMoreInfo: 'Añade más información',
    completeElementsVisibility: 'Completa estos elementos para mejorar tu visibilidad:',
    editProfileButton: 'Editar perfil',
    planBenefits: 'Ventajas de tu plan',
    featuredProfile: 'Perfil destacado',
    featuredProfileDesc: 'Aparece en las primeras posiciones de búsqueda',
    premiumBadge: 'Badge Premium',
    premiumBadgeDesc: 'Insignia visible que genera confianza',
    advancedStatistics: 'Estadísticas avanzadas',
    advancedStatsDesc: 'Métricas detalladas de tu perfil',
    higherVisibility: 'Mayor visibilidad',
    higherVisibilityDesc: 'Multiplica tus oportunidades de negocio',
    activatePremiumPlan: 'Activar plan premium',
    tipsToStandOutTitle: 'Consejos para destacar',
    addMorePhotosTip: 'Añade más fotos',
    addPhotosDesc: 'Los perfiles con 5+ fotos reciben un 80% más de contactos',
    respondFastTip: 'Responde rápido',
    respondFastDesc: 'Responder en menos de 1 hora mejora tu posicionamiento',
    askForReviewsTip: 'Pide valoraciones',
    askReviewsDesc: 'Las valoraciones aumentan la confianza y las conversiones',
    
    // Professional Dashboard
    welcomeProfessional: '¡Bienvenido, {{name}}!',
    profileActiveVisible: 'Tu perfil está activo y visible para clientes',
    completeProfileStart: 'Completa tu perfil para empezar a recibir clientes',
    views7Days: 'Visitas (7d)',
    messages7Days: 'Mensajes (7d)',
    favoritesCount: 'Favoritos',
    appearances7Days: 'Apariciones (7d)',
    viewPublicProfile: 'Ver tu perfil público',
    checkHowClientsView: 'Comprueba cómo ven tu perfil los clientes que buscan servicios como el tuyo',
    viewMyProfile: 'Ver mi perfil',
    editProfileDashboard: 'Editar perfil',
    updateDataPhotos: 'Actualiza tus datos, añade fotos de trabajos y mejora tu descripción',
    goToMyProfile: 'Ir a Mi Perfil',
    tipsToStart: 'Consejos para empezar',
    completeAllFields: 'Completa todos los campos obligatorios de tu perfil',
    addAtLeast3Photos: 'Añade al menos 3 fotos de trabajos realizados',
    writeClearDescription: 'Escribe una descripción clara y profesional de tus servicios',
    respondFastMessages: 'Responde rápido a los mensajes para mejorar tu posición en búsquedas',
    profileHidden: 'Perfil oculto',
    unread: 'sin leer',
  },
  en: {
    // Navigation
    searchFreelancers: 'Find Professionals',
    messages: 'Messages',
    favorites: 'Favorites',
    myProfile: 'My Profile',
    mySubscription: 'My Subscription',
    administration: 'Administration',
    viewPlans: 'View Plans',
    logout: 'Log Out',
    login: 'Log In',
    becomeFreelancer: 'Become a Professional',
    back: 'Back',
    contact: 'Contact',
    unread: 'unread',
    
    // Hero
    heroTitle: 'Find your trusted professional',
    heroSubtitle: 'Connect with verified professionals near you. Fast, easy and secure.',
    chooseHow: 'How do you want to use MisAutónomos?',
    imFreelancer: "I'm a professional",
    imClient: 'I need services',
    
    // Search
    filters: 'Search filters',
    search: 'Search service, company...',
    allCategories: 'All categories',
    allProvinces: 'All provinces',
    allCities: 'All cities',
    freelancersAvailable: 'professionals available',
    verifiedProfessionals: 'Verified professionals',
    noResults: 'No results found',
    tryDifferentFilters: 'Try different filters or search in another location',
    viewAll: 'View all',
    discoverFreelancers: 'Discover professionals',
    
    // Categories
    'Electricista': 'Electrician',
    'Fontanero': 'Plumber',
    'Carpintero': 'Carpenter',
    'Albañil / Reformas': 'Bricklayer / Renovations',
    'Pintor': 'Painter',
    'Jardinero': 'Gardener',
    'Transportista': 'Mover',
    'Autónomo de limpieza': 'Cleaning Professional',
    'Cerrajero': 'Locksmith',
    'Instalador de aire acondicionado': 'HVAC Technician',
    'Mantenimiento general': 'General Maintenance',
    'Mantenimiento de piscinas': 'Pool Maintenance',
    'Otro tipo de servicio profesional': 'Other Professional Service',
    
    // Cards & Profile
    verified: 'Verified',
    availableNow: 'Available now',
    until: 'Until',
    call: 'Call',
    whatsapp: 'WhatsApp',
    chat: 'Direct chat',
    workArea: 'Work area',
    hourRate: 'Average rate',
    noOpinions: 'No reviews yet',
    workGallery: 'Work Gallery',
    reviews: 'reviews',
    review: 'review',
    information: 'Information',
    schedule: 'Schedule',
    mondayFriday: 'Monday to Friday',
    weekends: 'Weekends & Holidays',
    everyday: 'Every day',
    averageRate: 'Average rate',
    email: 'Email',
    phone: 'Phone',
    website: 'Website',
    visitWebsite: 'Visit website',
    
    // Profile Completeness
    profileCompleteness: 'Profile completeness',
    completeProfileForMore: 'Complete your profile to receive more clients',
    goodProgress: 'Good progress, add more details',
    almostPerfect: 'Almost perfect! Just a few details missing',
    addTheseElements: 'Add these elements to improve your profile:',
    completeNow: 'Complete now',
    professionalName: 'Professional name',
    profilePicture: 'Profile picture',
    cifNif: 'Tax ID',
    telephoneContact: 'Phone',
    shortDescription: 'Short description',
    categoryPlural: 'Categories',
    photoGallery: 'Photo gallery',
    location: 'Location',
    paymentMethods: 'Payment methods',
    
    // Onboarding - Steps
    completeYourProfile: 'Complete your professional profile',
    step: 'Step',
    of: 'of',
    identity: 'Identity',
    activity: 'Activity',
    zoneAndAvailability: 'Location & Availability',
    pricesAndWorkMethod: 'Pricing & Work Method',
    portfolioPhotos: 'Portfolio (photos)',
    consentsAndLegal: 'Consents & Legal',
    finalReview: 'Final Review',
    next: 'Next',
    saving: 'Saving...',
    publishing: 'Publishing...',
    publishProfile: 'Publish profile',
    
    // Onboarding - Identity Step
    professionalNameLabel: 'Professional name *',
    professionalNamePlaceholder: 'e.g., John Smith - Electrician',
    characters: 'characters',
    cifNifLabel: 'Tax ID *',
    cifNifPlaceholder: '12345678A or B12345678',
    contactEmailLabel: 'Contact email *',
    contactEmailPlaceholder: 'your@email.com',
    contactPhoneOptional: 'Contact phone *',
    contactPhonePlaceholder: '612345678 or +34612345678',
    noPhoneOnlyChat: 'Without a phone, clients can only contact you via internal chat',
    visibleContactMethods: 'Visible contact methods',
    selectHowClientsContact: 'Select how you want clients to contact you',
    internalChat: 'Internal chat',
    alwaysActive: 'Always active',
    phoneCall: 'Phone call',
    requiresPhone: 'Requires phone',
    addPhoneFirstWhatsApp: 'Add a valid phone number first',
    addPhoneFirstCall: 'Add a valid phone number first',
    
    // Onboarding - Activity Step
    serviceCategories: 'Service category *',
    selectAtLeastOne: '(select one)',
    selected: 'selected',
    selectedPlural: 'selected',
    specifyYourService: 'Specify your service *',
    specifyServicePlaceholder: 'e.g., Solar panel installer, HVAC technician, etc.',
    describeYourActivity: 'Describe your professional activity (minimum 3 characters)',
    shortDescriptionLabel: 'Short description *',
    shortDescriptionMax: '(max 220 characters)',
    shortDescriptionPlaceholder: 'Briefly describe your services...',
    minimum20: '(min 20)',
    detailedDescriptionOptional: 'Detailed description (optional)',
    detailedDescriptionPlaceholder: 'Add details about your experience, services, etc.',
    
    // Onboarding - Location Step
    indicateMainLocation: 'Set your main location and work area. Clients will find you in these areas.',
    province: 'Province',
    selectYourProvince: 'Select province',
    city: 'City',
    locality: 'City',
    selectFromList: '(select from list)',
    selectYourCity: 'Select city',
    asMainCity: '(optional)',
    onlyFromList: 'Select from the list. If your city is not listed, choose the nearest one.',
    neighborhoodOptional: 'Neighborhood / District (optional)',
    neighborhoodPlaceholder: 'e.g., Downtown, Brooklyn, Queens...',
    specifyNeighborhood: 'Specify a specific neighborhood or area (optional)',
    yourMainLocation: 'Your main location:',
    serviceRadius: 'Service radius *',
    onlyMyZone: 'Local area only',
    cityAndSurroundings: 'City & surroundings',
    metropolitanArea: 'Metro area',
    provinceWide: 'Entire province',
    multipleProvinces: 'Multiple provinces',
    howFarTravel: 'How far are you willing to travel?',
    availability: 'Availability',
    whenCanYouWork: 'When can you work?',
    weekdays: 'Weekdays (Mon–Fri)',
    workMondayFriday: 'Monday to Friday',
    weekendsAndHolidays: 'Weekends & holidays',
    workWeekendsHolidays: 'Saturdays, Sundays & holidays',
    allWeek: 'All week',
    availableAnyDay: 'Available any day',
    startTime: 'Start time *',
    endTime: 'End time *',
    schedulePreview: 'Schedule',
    
    // Onboarding - Pricing Step
    baseRateOptional: 'Base rate (€/hour) - OPTIONAL',
    baseRatePlaceholder: 'e.g., 35 (leave empty to hide)',
    emptyNoRate: 'Leave empty if you prefer not to display your rate',
    invoiceType: 'Business type *',
    freelancer: 'Self-employed',
    company: 'Company',
    other: 'Other',
    acceptedPaymentMethods: 'Accepted payment methods *',
    selectAtLeastOnePayment: 'Select at least one payment method',
    card: 'Card',
    transfer: 'Bank Transfer',
    cash: 'Cash',
    bizum: 'Bizum',
    selectedPayment: 'Selected',
    paymentMethodsSelected: 'payment method(s) selected',
    
    // Onboarding - Portfolio Step
    workPhotos: 'Work portfolio (photos) - OPTIONAL',
    minimum1Photo: '',
    clickToAddPhoto: 'Click to add photo',
    photo: 'Photo',
    photosUploaded: 'photo(s) uploaded',
    mainPhoto: 'Main',
    
    // Onboarding - Legal Step
    readAndAcceptConsents: 'Read and accept the required consents to publish your profile',
    acceptAllConsents: 'Accept all',
    allConsentsAccepted: 'All consents accepted',
    termsAndConditionsLabel: 'Terms and Conditions',
    acceptTermsAndConditions: 'I have read and accept the',
    termsAndConditions: 'Terms and Conditions',
    ofPlatformUse: 'of the MisAutónomos platform',
    privacyPolicyLabel: 'Privacy Policy',
    acceptPrivacyPolicy: 'I accept the',
    privacyPolicy: 'Privacy Policy',
    andDataTreatment: 'and the processing of my personal data per GDPR',
    contactConsentLabel: 'Contact Consent',
    consentClientContact: 'I consent to being contacted by clients through the platform for quotes and services',
    
    // Onboarding - Review Step
    reviewAllInfo: 'Review all your information before publishing your professional profile. You can edit it later from your user panel.',
    edit: 'Edit',
    name: 'Name',
    nif: 'Tax ID',
    contactMethods: 'Contact methods',
    internalChatMethod: 'Internal Chat',
    whatsappMethod: 'WhatsApp',
    phoneCallMethod: 'Phone Call',
    none: 'None',
    notSpecified: 'Not specified',
    specificService: 'Specific service',
    description: 'Description',
    noDescription: 'No description',
    locationAndAvailability: 'Location and Availability',
    neighborhood: 'Neighborhood',
    availabilityColon: 'Availability:',
    scheduleColon: 'Schedule:',
    ratesAndWorkMethod: 'Rates and Work Method',
    baseRate: 'Base rate',
    invoicingType: 'Invoice type',
    paymentMethods: 'Payment methods',
    photos: 'Photos',
    legalConfirmations: 'Legal confirmations',
    acceptTerms: 'I accept the terms and conditions',
    acceptPrivacy: 'I accept the privacy policy',
    consentContact: 'I consent to being contacted by clients',
    
    // Onboarding - Success
    profileActiveTitle: 'Your professional profile is active!',
    visibleInSearches: 'You are now visible in',
    startReceivingContacts: 'Start receiving contacts from clients interested in your professional services.',
    profileActive: 'Profile active',
    visibleInSearch: 'Visible in searches',
    readyForClients: 'Ready for clients',
    viewMyPublicProfile: 'View my public profile',
    viewClientSearches: 'View client searches',
    editMyProfile: 'Edit my profile',
    tipsToStandOut: 'Tips to stand out',
    addMorePhotos: 'Keep your profile updated with recent photos of your work',
    respondFast: 'Respond quickly to messages to improve your search ranking',
    askForReviews: 'Ask satisfied clients for reviews',
    needHelp: 'Need help? Contact support:',
    restrictedAccess: 'Restricted access',
    professionalOnlyPage: 'This page is only for professionals. If you want to offer your services, you must first select a plan.',
    viewAvailablePlans: 'View available plans',
    
    // Validation errors
    professionalNameMinChars: 'Professional name must be at least 2 characters',
    cifNifMinChars: 'Tax ID must be at least 8 characters',
    invalidEmail: 'Invalid email address',
    phoneRequired: 'Phone number is required and must be at least 9 digits',
    selectAtLeastOneContactMethod: 'Select at least one contact method',
    selectAtLeastOneCategory: 'Select a category',
    specifyServiceIfOther: 'Please specify your service when selecting "Other Professional Service"',
    serviceSpecMinChars: 'Service description must be at least 3 characters',
    shortDescriptionMinChars: 'Short description must be at least 20 characters',
    selectProvince: 'Select a province',
    selectCity: 'Select a city',
    selectAvailabilityType: 'Select availability type',
    selectAtLeastOnePaymentMethod: 'Select at least one payment method',
    uploadAtLeast1Photo: 'Upload at least 1 photo',
    acceptTermsAndConditionsError: 'You must accept the Terms and Conditions',
    acceptPrivacyPolicyError: 'You must accept the Privacy Policy',
    consentClientContactError: 'You must consent to client contact',
    errorSavingStep: 'Error saving: ',
    pleaseVerifyData: '. Please check your data.',
    completeStep: 'Complete step',
    beforePublishing: 'before publishing',
    errorSavingProfile: 'Error saving profile',
    profileCompletedAndPublished: 'Profile published successfully!',
    photoUploadSuccess: 'Photo uploaded successfully',
    photoUploadError: 'Error uploading photo',
    terms: 'terms',
    privacy: 'privacy',
    noPhotosAdded: 'No photos yet',
    
    // Client Onboarding
    createClientAccount: 'Create your account',
    completeDataToSearch: 'Complete your info to start finding professionals',
    freeNoHiddenCosts: '100% FREE - No hidden fees',
    emailVerificationSent: 'Your account will be created and you will receive a verification email',
    fullName: 'Full name',
    fullNamePlaceholder: 'e.g., John Smith',
    emailCantChange: 'Account email (cannot be changed)',
    emailVerificationInfo: 'You will receive a verification email at this address',
    whatServicesLooking: 'What services are you looking for? *',
    createMyClientAccount: 'Create account',
    completeRegistration: 'Complete registration',
    redirectingToRegistration: 'Redirecting...',
    savingYourData: 'Saving your data and setting up your account',
    redirectInSeconds: 'You will be redirected shortly...',
    alreadyProfessionalAccount: 'You already have a professional account',
    cantCreateClientAccount: 'Your account is already configured as a professional',
    redirectingToProfile: 'Redirecting to your profile...',
    freeBenefit: '100% Free',
    noHiddenCosts: 'No hidden fees',
    verifiedProfessionals: 'Verified professionals',
    realReviews: 'Real reviews',
    directChat: 'Direct chat',
    immediateContact: 'Instant contact',
    redirecting: 'Redirecting...',
    creatingAccount: 'Creating account...',
    freeForClients: 'Search and contact professionals completely free',
    
    // Subscription Management
    manageProfessionalPlan: 'Manage your plan',
    backToProfile: 'Back to Profile',
    noActiveSubscription: 'No active subscription',
    needPlanToAppear: 'Subscribe to a plan to appear in search results and receive client inquiries',
    verifyPaymentAdmin: 'Verify payment (Admin)',
    verifying: 'Verifying...',
    yourPlanInfo: 'Plan details',
    currentPlan: 'Current plan',
    active: 'Active',
    canceled: 'Canceled',
    finished: 'Expired',
    trial: 'Trial',
    startDate: 'Start date',
    renewalExpiration: 'Renewal / Expiration',
    days: 'days',
    profileVisibleOk: 'Your profile is visible to all clients',
    trialActive: 'Trial period active. Your profile is visible to clients',
    daysRemainingTrial: 'days left in your free trial. You will be charged automatically if you don\'t cancel before this date',
    subscriptionCanceledActive: 'Subscription canceled. Active until',
    profileVisibleFor: 'Your profile remains visible for',
    moreDays: 'more days',
    subscriptionFinishedHidden: 'Subscription expired. Your profile is hidden',
    considerReactivating: 'Reactivate your plan to appear in searches again',
    upgradeYourPlan: 'Upgrade plan',
    saveUpTo: 'Save up to €138/year with quarterly or annual plans',
    viewSuperiorPlans: 'View plans',
    reactivateYourPlan: 'Reactivate plan',
    appearInSearches: 'Get back in search results and receive new clients',
    cancelSubscription: 'Cancel subscription',
    cancelTrialNoCharge: 'Cancel during trial: no charge. Your profile will be hidden immediately',
    cancelHideProfile: 'Your profile will be hidden immediately, but you keep access until expiration',
    changePlan: 'Change plan',
    exploreOtherPlans: 'Explore plans that fit your needs',
    viewAllPlans: 'View all plans',
    confirmCancelSubscription: 'Cancel subscription?',
    ifYouCancel: 'If you cancel:',
    noChargeTrialCanceled: 'NO charge (trial canceled)',
    profileHidesImmediately: 'Profile hidden immediately',
    canReactivateAnytime: 'Reactivate anytime',
    profileHidesFromSearch: 'will be hidden from search',
    noNewClientContacts: 'No new client inquiries',
    accessUntil: 'Access retained until',
    canReactivateSubscription: 'Reactivate subscription anytime',
    areYouSureContinue: 'Are you sure?',
    noKeepActive: 'No, keep it',
    canceling: 'Canceling...',
    yesCancelSubscription: 'Yes, cancel',
    
    // Reviews
    reviewsTitle: 'Client Reviews',
    noReviewsYet: 'No reviews yet',
    beFirstReview: 'Be the first to review',
    speed: 'Response time',
    communication: 'Communication',
    quality: 'Quality',
    priceSatisfaction: 'Value',
    reportReview: 'Report',
    inappropriate: 'Inappropriate',
    
    // Messages
    conversations: 'Conversations',
    noConversations: 'No conversations',
    startChatting: 'Start chatting with professionals',
    writeMessage: 'Write a message...',
    send: 'Send',
    loadingMessages: 'Loading messages...',
    user: 'User',
    you: 'You',
    professional: 'Professional',
    client: 'Client',
    online: 'Online',
    selectConversation: 'Select a conversation',
    chooseContactToChat: 'Choose a contact to start chatting',
    enterToSend: 'Press Enter to send, Shift+Enter for new line',
    messageSent: 'Message sent',
    sendMessageError: 'Error sending message',
    prepareMessageError: 'Error preparing message: ',
    
    // Review Dialog
    rateServiceOf: 'Rate {{name}}',
    reviewHelpfulDescription: 'Your review helps others make informed decisions',
    rapidez: 'Response time',
    comunicacion: 'Communication',
    calidadTrabajo: 'Work quality',
    relacionCalidadPrecio: 'Value for money',
    tellExperienceOptional: 'Share your experience (optional)',
    experiencePlaceholder: 'How was your experience with this professional?',
    tip: 'Tip',
    honestReviewsHelpful: 'Honest reviews help the community',
    warning: 'Warning',
    alreadyReviewedMessage: 'You already reviewed this professional',
    rateAllAspects: 'Please rate all aspects',
    commentMinLength: 'Comments must be at least 10 characters',
    reviewSuccess: 'Review published',
    alreadyReviewed: 'Already reviewed',
    reviewError: 'Error publishing review',
    alreadyReviewedInfo: 'You already reviewed this professional',
    bidirectionalConversationRequired: 'Reviews require a two-way conversation',
    cannotLeaveReviewNow: 'Cannot review at this time',
    sending: 'Sending...',
    publishReview: 'Publish',
    noMessagesInConversation: 'No messages yet',
    contactProfessionalToStart: 'Contact a professional to start',
    loadingMessaging: 'Loading...',
    messagesPageDescription: 'Manage conversations with professionals',
    
    // Favorites
    myFavorites: 'My Favorites',
    noFavorites: 'No favorites yet',
    addFavorites: 'Save your preferred professionals here',
    remove: 'Remove',
    
    // Footer
    tagline: 'Your trusted professional',
    platformDescription: 'Connecting professionals with clients across Spain',
    forProfessionals: 'For Professionals',
    forClients: 'For Clients',
    navigation: 'Navigation',
    legal: 'Legal',
    plansAndPricing: 'Plans & Pricing',
    createProfile: 'Create Profile',
    joinAdvantages: 'Why Join',
    helpCenter: 'Help Center',
    createFreeAccount: 'Sign Up Free',
    faq: 'FAQ',
    cookiePolicy: 'Cookie Policy',
    legalNotice: 'Legal Notice',
    allRightsReserved: 'All rights reserved',
    
    // Cookies Banner
    cookiesBannerTitle: 'This website uses cookies',
    cookiesBannerDescription: 'We use cookies to improve your experience. Click "Accept all" to accept all cookies, or manage your preferences.',
    acceptAllCookies: 'Accept All',
    acceptEssentialCookies: 'Essential Only',
    configureCookies: 'Settings',
    rejectAllCookies: 'Reject All',
    cookiePreferences: 'Cookie Preferences',
    cookiePreferencesDescription: 'Choose which cookies to allow',
    essentialCookies: 'Essential Cookies',
    essentialCookiesDescription: 'Required for site functionality (authentication, security, navigation). Cannot be disabled.',
    analyticsCookies: 'Analytics Cookies',
    analyticsCookiesDescription: 'Help us understand user behavior to improve the site (Google Analytics)',
    marketingCookies: 'Marketing Cookies',
    marketingCookiesDescription: 'Used for relevant ads and campaign measurement',
    savePreferences: 'Save Settings',
    learnMoreCookies: 'Learn more:',
    
    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    previous: 'Previous',
    confirm: 'Confirm',
    close: 'Close',
    
    // MyProfile page
    myProfileTitle: 'My Profile',
    manageYourInfo: 'Manage your information',
    manageProfessionalProfile: 'Manage your professional profile',
    visibleToClients: 'Visible to clients',
    profileHidden: 'Profile hidden',
    editProfile: 'Edit Profile',
    becomeProfessional: 'Become a Professional',
    cancelEdit: 'Cancel',
    saveChanges: 'Save Changes',
    savingChanges: 'Saving...',
    profileUpdatedSuccess: 'Your profile has been updated',
    wantToOfferServices: 'Want to offer your services?',
    becomeProfessionalAppear: 'Become a professional and appear in client searches',
    viewPlansButton: 'View Plans',
    personalInfo: 'Personal Information',
    professionalProfile: 'Professional Profile',
    portfolio: 'Portfolio',
    personalInfoSection: 'Personal information',
    fullNameLabel: 'Full name',
    phoneLabel: 'Phone',
    cityLabel: 'City',
    accountType: 'Account type',
    professionalAccount: 'Professional',
    clientAccount: 'Client',
    dangerZone: 'Danger zone',
    dangerZoneDescription: 'This will permanently delete your account, profile, messages, favorites, reviews, and cancel your active subscription.',
    deleteMyAccount: 'Delete my account',
    
    // Professional Identity
    professionalIdentity: 'Professional Identity',
    professionalNameRequired: 'Professional name *',
    professionalNamePlaceholder2: 'Your Company Ltd.',
    taxIdLabel: 'Tax ID / VAT',
    taxIdPlaceholder: '12345678A',
    yearsExperience: 'Years of experience',
    yearsPlaceholder: '5',
    contactEmailLabel2: 'Contact email',
    contactPhoneLabel: 'Contact phone',
    certificationsLabel: 'Certifications and qualifications',
    certificationPlaceholder: 'Professional certification, degree...',
    
    // Services & Description
    servicesDescription: 'Services & Description',
    serviceCategoriesLabel: 'Service categories',
    specifyService: 'Specify your service',
    specifyServicePlaceholder2: 'Solar panel installer...',
    shortDescriptionLimit: 'Short description (220 characters)',
    shortDescPlaceholder: 'Briefly describe your services...',
    detailedDescriptionSEO: 'Detailed description (for SEO)',
    detailedDescPlaceholder: 'Experience, specialties, featured projects...',
    
    // Location & Availability Section
    locationAvailability: 'Location & Availability',
    provinceLabel: 'Province',
    selectProvincePlaceholder: 'Select province',
    cityLabel2: 'City',
    cityPlaceholder: 'Madrid',
    neighborhoodLabel: 'Neighborhood / District (optional)',
    neighborhoodPlaceholder2: 'Downtown, Chamartín...',
    serviceRadiusLabel: 'Service radius',
    serviceRadius5: '5 km - Local area only',
    serviceRadius10: '10 km - City',
    serviceRadius25: '25 km - Metro area',
    serviceRadius50: '50 km - Province',
    serviceRadius100: '100+ km - Multiple provinces',
    availabilityLabel: 'Availability',
    availabilityWeekdays: 'Weekdays (Mon-Fri)',
    availabilityWeekends: 'Weekends & holidays',
    availabilityAllWeek: 'All week',
    startTimeLabel: 'Start time',
    endTimeLabel: 'End time',
    
    // Rates & Work Method
    ratesWorkMethod: 'Rates & Work Method',
    baseRateHourly: 'Base rate (€/hour) - optional',
    baseRatePlaceholder2: '35',
    businessTypeLabel: 'Business type',
    selfEmployed: 'Self-employed',
    limitedCompany: 'Limited company',
    others: 'Other',
    acceptedPaymentMethodsLabel: 'Accepted payment methods',
    cardPayment: 'Card',
    bankTransfer: 'Bank Transfer',
    cashPayment: 'Cash',
    bizumPayment: 'Bizum',
    
    // Online Presence
    onlinePresence: 'Online Presence',
    websiteLabel: 'Website',
    websitePlaceholder: 'https://yourwebsite.com',
    facebookLabel: 'Facebook',
    facebookPlaceholder: 'https://facebook.com/yourpage',
    instagramLabel: 'Instagram',
    instagramPlaceholder: 'https://instagram.com/yourprofile',
    linkedinLabel: 'LinkedIn',
    linkedinPlaceholder: 'https://linkedin.com/in/yourprofile',
    tiktokLabel: 'TikTok',
    tiktokPlaceholder: 'https://tiktok.com/@yourprofile',
    
    // Work Gallery
    workGalleryTitle: 'Work Gallery',
    workGalleryDescription: 'Upload photos of completed projects. Maximum 10 images. The first one will be your main photo.',
    clickToAddPhotoGallery: 'Click to add photo ({{count}}/10)',
    photoAlt: 'Photo {{number}}',
    mainPhotoLabel: 'Main',
    
    // Delete Account Dialog
    deleteAccountTitle: 'Delete your account permanently?',
    deleteAccountWarning: 'WARNING: This action is IRREVERSIBLE',
    willBeDeleted: 'The following will be permanently deleted:',
    yourAccountProfile: 'Your account and complete profile',
    allMessagesConversations: 'All your messages and conversations',
    favoritesReviews: 'Your favorites and reviews',
    professionalProfilePhotos: 'Your professional profile and photos',
    activeSubscription: 'Your active subscription',
    cancelButton: 'Cancel',
    deletingAccount: 'Deleting...',
    yesDeletePermanently: 'Yes, delete permanently',
    accountDeleted: 'Your account has been deleted',
    errorDeletingAccount: 'Error deleting your account',
    
    // Premium Dashboard
    premiumPanel: 'Premium Dashboard',
    enjoyPlanBenefits: 'Enjoy all your plan benefits',
    upgradePlanUnlock: 'Upgrade to unlock all features',
    premium: 'Premium',
    profileViews30Days: 'Profile views (30 days)',
    perDay: 'per day',
    messagesReceived: 'Messages received',
    last30Days: 'Last 30 days',
    searchAppearances: 'Search appearances',
    contactClicks: 'Contact clicks',
    phoneWhatsAppEtc: 'Phone, WhatsApp, etc.',
    unlockStatistics: 'Unlock your statistics',
    premiumPlanMetrics: 'With a premium plan you can see all metrics and optimize your profile',
    viewPremiumPlans: 'View premium plans',
    profileCompletenessTitle: 'Profile Completeness',
    percentComplete: '{{percentage}}% complete',
    excellent: 'Excellent!',
    goodProgressStatus: 'Good progress',
    addMoreInfo: 'Add more info',
    completeElementsVisibility: 'Complete these to improve visibility:',
    editProfileButton: 'Edit profile',
    planBenefits: 'Plan Benefits',
    featuredProfile: 'Featured Profile',
    featuredProfileDesc: 'Appears in top search positions',
    premiumBadge: 'Premium Badge',
    premiumBadgeDesc: 'Visible badge that builds trust',
    advancedStatistics: 'Advanced Statistics',
    advancedStatsDesc: 'Detailed profile metrics',
    higherVisibility: 'Higher Visibility',
    higherVisibilityDesc: 'Multiply your business opportunities',
    activatePremiumPlan: 'Activate premium plan',
    tipsToStandOutTitle: 'Tips to Stand Out',
    addMorePhotosTip: 'Add more photos',
    addPhotosDesc: 'Profiles with 5+ photos get 80% more inquiries',
    respondFastTip: 'Respond quickly',
    respondFastDesc: 'Responding in under 1 hour boosts your ranking',
    askForReviewsTip: 'Ask for reviews',
    askReviewsDesc: 'Reviews increase trust and conversions',
    
    // Professional Dashboard
    welcomeProfessional: 'Welcome, {{name}}!',
    profileActiveVisible: 'Your profile is active and visible to clients',
    completeProfileStart: 'Complete your profile to start receiving clients',
    views7Days: 'Views (7d)',
    messages7Days: 'Messages (7d)',
    favoritesCount: 'Favorites',
    appearances7Days: 'Appearances (7d)',
    viewPublicProfile: 'View your public profile',
    checkHowClientsView: 'Check how clients see your profile when searching for services like yours',
    viewMyProfile: 'View my profile',
    editProfileDashboard: 'Edit profile',
    updateDataPhotos: 'Update your info, add photos and improve your description',
    goToMyProfile: 'Go to My Profile',
    tipsToStart: 'Tips to get started',
    completeAllFields: 'Complete all required profile fields',
    addAtLeast3Photos: 'Add at least 3 photos of completed work',
    writeClearDescription: 'Write a clear and professional service description',
    respondFastMessages: 'Respond quickly to messages to improve search position',
    
    // Other missing
    noPhotosAdded: 'No photos added',
    phoneRequired: 'Phone number required (minimum 9 digits)',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('es');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') || 'es';
    setLanguage(savedLang);
    document.documentElement.lang = savedLang;
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations.es[key] || key;
    
    Object.keys(params).forEach(param => {
      text = text.replace(`{{${param}}}`, params[param]);
    });
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export default function LanguageSwitcher({ variant = "default" }) {
  const { language, changeLanguage } = useLanguage();

  if (variant === "compact") {
    return (
      <div className="flex gap-1 bg-gray-100 rounded-lg p-1">
        <button
          onClick={() => changeLanguage('es')}
          className={`px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
            language === 'es'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'text-gray-600 hover:bg-gray-200'
          }`}
          aria-label="Cambiar idioma a Español"
        >
          ES
        </button>
        <button
          onClick={() => changeLanguage('en')}
          className={`px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
            language === 'en'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'text-gray-600 hover:bg-gray-200'
          }`}
          aria-label="Change language to English"
        >
          EN
        </button>
      </div>
    );
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="hover:bg-gray-100" aria-label="Cambiar idioma">
          <Globe className="h-5 w-5 text-gray-600" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="bg-white">
        <DropdownMenuItem
          onClick={() => changeLanguage('es')}
          className={language === 'es' ? 'bg-blue-50 text-blue-900 font-semibold' : ''}
        >
          🇪🇸 Español
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => changeLanguage('en')}
          className={language === 'en' ? 'bg-blue-50 text-blue-900 font-semibold' : ''}
        >
          🇬🇧 English
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}